### ISSUE TITLE
Define functions exposing to JS binding

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#10]

**Comment by huningxin** [comment]
Refer to https://docs.google.com/spreadsheets/d/1uUbKcXBRVDX9oHp6cTCvvSqozqz42BaRcznwxwGFUEM/edit#gid=0

**Comment by huningxin** [comment]
@sajjadt , do we only export functions marked in pink in above spreadsheet?

**Comment by huningxin** [comment]
I propose to use a white list to control the classes and functions to export without adding new directives. The white list is within `js` module.

**Comment by huningxin** [comment]
Paste @sajjadt 's original idea here. Please feel free to update.

"
I've also attached the list of important OpenCV functions that we want in our binding. This helps making the generated binary much smaller. We also want to cover only these functions in tutorials. To generate bindings for these functions, I suggest to define a new Macro e.g. CV_WRAP_JS and annotate the functions with it. Then binding generator can recognize these functions.
"

**Comment by huningxin** [comment]
Another way might be WebIDL Binder of emscripten: https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html. I will do some investigation and report back.

**Comment by huningxin** [comment]
Send #34 as white list solution which is within `js` module.

The output `opencv.js` is now 6.6 MB. 

@sajjadt , please take a look.

**Comment by sajjadt** [comment]
Looks nice! Library size is still high, by closing #27 it's going to shrink a lot and become acceptable.

**Comment by huningxin** [comment]
@sajjadt , @pancx merged the #34 for not blocking the test cases development. I opened #40 to track your proposal. Let's keep discussion there.
