### ISSUE TITLE
[ImgProc]  Something wrong in cv.MatVector();

### ISSUE THREAD

**Issue by ganwenyao** [huningxin/opencv#100]
```js
var src = cv.imread("approxPolyDPCanvasInput");
var dst = new cv.Mat.zeros(src.cols, src.rows, cv.CV_8UC3);
cv.cvtColor(src, src, cv.ColorConversionCodes.COLOR_RGBA2GRAY.value, 0);
cv.threshold(src, src, 177, 200, cv.ThresholdTypes.THRESH_BINARY.value);
var contours  = new cv.MatVector();
var hierarchy = new cv.Mat();
var polyMatVector = new cv.MatVector();
var polyMat = new cv.Mat();
cv.findContours(src, contours, hierarchy, cv.RetrievalModes.RETR_CCOMP.value, cv.ContourApproximationModes.CHAIN_APPROX_SIMPLE.value, [0,0]);
cv.approxPolyDP(contours.get(20), polyMatVector.get(20), 3, true);
```
@huningxin There is something wrong when I use cv.approxPolyDP(contours.get(20), polyMatVector.get(20), 3, true), but it works successfully when I use cv.approxPolyDP(contours.get(20), polyMat, 3, true).

**Comment by huningxin** [comment]
@ganwenyao , in your case, `polyMatVector.get(20)` returns `undefined` as its size is 0 with default constructor `var polyMatVector = new cv.MatVector();`.

You can resize it by e.g. `polyMatVector.resize(21, new cv.Mat())`. Then `polyMatVector.get(20)` will return a Mat.

**Comment by ganwenyao** [comment]
@huningxin There is still something wrong in cv.approxPolyDP(contours.get(i), polyMatVector.get(i), 3, true).

**Comment by huningxin** [comment]
We have workaround to use a mat to get the return value then push to the vector like
```
for (let i = 0; i < contours.size(); i++) {
    cv.approxPolyDP(contours.get(i), polyMat, 3, true);
    polyMatVector.push_back(polyMat);
}
```
I will look into the failure of getting value of `polyMatVector.get(i)` later.

**Comment by huningxin** [comment]
` cv.approxPolyDP` will invoke `mat.copyTo` for 2nd parameter. `copyTo` internally will invoke `create` which will reallocate memory. The 2nd paramter is `polyMatVector.get(i)` which actually copies a mat to return. So only the mat copy gets new memory, the mat inside `polyMatVector` doesn't get updated. 

BTW, the mat from `polyMatVector.get(i)` should be deleted.

**Comment by huningxin** [comment]
Close this issue as it is emscripten convention.
