### ISSUE TITLE
Show warning when the "tryit" code throw exception

### ISSUE THREAD

**Issue by pancx** [huningxin/opencv#104]
Users will never know errors occor, if they haven't opened the console.
So we should reminder users by emitting events in web.

**Comment by pancx** [comment]
Or provide an output box to display errors and warnings.

**Comment by ganwenyao** [comment]
We can use try-throw-catch like this:
```js
 if (canvas === null || !(canvas instanceof HTMLCanvasElement))  { throw "Please input the valid canvas id." ; return; }
try {
    eval(cvtColorText);
    cvtColorErr.innerHTML = " ";
} catch(err) {
    cvtColorErr.innerHTML = err;
}
```
The following picture is the result:
![pic](https://user-images.githubusercontent.com/26854899/28551833-0e587042-70b0-11e7-8012-f572f257238a.png)

**Comment by huningxin** [comment]
"gui feature" doesn't support this feature. @pancx , please add it. Thanks!
