### ISSUE TITLE
[Doc] Check whether cv is ready before register the onload event

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#112]
Current tutorials use following code to monitor opencv.js loading and enable UI when it is ready. e.g. in https://github.com/huningxin/opencv/blob/js/doc/js_tutorials/js_gui/js_image_display/js_image_display.markdown
```
document.getElementById("opencvjs").onload = function() {
    document.getElementById("tryIt").disabled = false;
};
```

It has issue that this code might be executed after `onload` event fired. So it is better to check whether cv is ready before register to `onload` event.
```
function enableElements() {
  document.getElementById("tryIt").disabled = false;
}

if (typeof cv !== 'undefined')
  enableElements();
else
  document.getElementById("opencvjs").onload = enableElements();
```

@pancx @ganwenyao , please review. If it is OK, please apply in your tutorials. Thanks!

**Comment by pancx** [comment]
Done in #114
