### ISSUE TITLE
JS tutorial for image processing - part 2

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#113]
Remaining tasks from https://github.com/huningxin/opencv/issues/18

- [x] Contours in OpenCV
- [x] Histograms in OpenCV
- [x] Image Transforms in OpenCV
- [x] Template Matching
- [x] Hough Line Transform
- [x] Hough Circle Transform
- [x] Image Segmentation with Watershed Algorithm
- [x] Interactive Foreground Extraction using GrabCut Algorithm

**Comment by ganwenyao** [comment]
The following google spreadsheet includes functions which are used in image processing turotials:
https://docs.google.com/a/intel.com/spreadsheets/d/17brxaSvp88sEXCZjkYxI88OOXGQW_9Mwsw2D0abRi9o/edit?usp=sharing

**Comment by huningxin** [comment]
This is closed by https://github.com/huningxin/opencv/pull/143. Nice job!
