### ISSUE TITLE
[ImgProc] some opencv(js) functions are exposed to some improper opencv(C++) overloaded member functions

### ISSUE THREAD

**Issue by ganwenyao** [huningxin/opencv#117]
* We need cv.calcHist (image, nimages, channels, mask, hist, dims, histSize, ranges, uniform = true, accumulate = false) but in bindings, it's exposed to cv.calcHist(image, channels, mask, hist, histSize, ranges, accumulate) which is an overloaded member function.
*  cv.calcBackProject() have similar problem.

**Comment by huningxin** [comment]
We will revisit this issue if someone needs this function. Thanks!
