### ISSUE TITLE
[video] BindingError in cv.calcOpticalFlowPyrLK

### ISSUE THREAD

**Issue by pancx** [huningxin/opencv#119]
cv.calcOpticalFlowPyrLK has three params for output, InputOutputArray nextPts, OutputArray status,
 OutputArray err. In reality, their types are vector of 2D points, vector of unsigned chars, vector of errors.
But we expose them all as cv.Mat.

**Comment by ganwenyao** [comment]
BindingError {name: "BindingError", message: "Cannot pass "[object Object]" as a Mat", stack: 
````js
var src1 = cv.imread("cvtColorCanvasInput");
var src2 = cv.imread("inRangeCanvasInput");
var prevImg = new cv.Mat(); 
var nextImg = new cv.Mat(); 
cv.cvtColor(src1, prevImg, cv.COLOR_RGBA2GRAY, 0);
cv.cvtColor(src2, nextImg, cv.COLOR_RGBA2GRAY, 0);
var prevPts = new cv.Mat(); 
var nextPts = new cv.Mat();
var status = new cv.Mat();
var err = new cv.Mat();
cv.goodFeaturesToTrack(prevImg, prevPts, 100, 0.3, 7);
cv.calcOpticalFlowPyrLK(prevImg, nextImg, prevPts, nextPts, status, err);
```

**Comment by huningxin** [comment]
It looks like there are some variable renaming issue in your code. Please use `let`, e.g. `let status = new cv.Mat();` in sample code. It works for me.

**Comment by pancx** [comment]
Window has member named status, which was passed to cv.calcOpticalFlowPyrLK(prevImg, nextImg, prevPts, nextPts, status, err)

**Comment by huningxin** [comment]
Thanks for the inputs. So this is not an issue. Let's close it.
