### ISSUE TITLE
[video] Provide video file for video analysis tutorials

### ISSUE THREAD

**Issue by pancx** [huningxin/opencv#120]
Video analysis tutorials need video files for demos.
But there is no video file in opencv source. 
Should we provide video files or links or just screenshot?

**Comment by pancx** [comment]
There are some videos in sample/data.
In addition, html5 <video> only supports Ogg, WebM(VP8/VP9) or MP4(H.264).

**Comment by huningxin** [comment]
I would suggest to reuse the video files from opencv source. Can we convert them into web compatible one, say WebM?

**Comment by pancx** [comment]
MP4 was more widely used. So I will convert some videos in opencv source to MP4(H.264), and put them in js_assets for demos.

**Comment by pancx** [comment]
resolved by #142 .
In Optical Flow and Background Subtraction tutorials we use box.mp4 in opencv source directly.
For Meanshift and Camshift tutorial, I add a cup.mp4 cause there is no applicable video in opencv source.

**Comment by sajjadt** [comment]
There are bunch of videos in opencv_extra [repo](https://github.com/opencv/opencv_extra). Also Xiph.org has raw video data that we can use.

**Comment by huningxin** [comment]
> There are bunch of videos in opencv_extra repo. Also Xiph.org has raw video data that we can use.

Good point, @sajjadt !

@pancx , could you please investigate whether we can reuse those videos?
