### ISSUE TITLE
Loading classifiers from Memory

### ISSUE THREAD

**Issue by sajjadt** [huningxin/opencv#132]
We can load classifier models from memory in OpenCV using ```CascadeClassifier::read```. This is however does not support old cascade format. We can export that  function plus ```cv::FileStorage``` or export a helper function like the following one.

```cpp
// Load Haar Model
void loadModelFromMem(cv::CascadeClassifier& classifier, const std::string & model_str) {
  cv::FileStorage fs(model_str, FileStorage::READ | FileStorage::MEMORY);
  classifier.read(fs.getFirstTopLevelNode());
}
```
This is how I instantiated the classifier in Nodejs.
```js
var haar = new cv.CascadeClassifier();
var classifier_model = fs.readFileSync(assets_dir + '/frontal_face.xml');
haar.loadModelFromMem(classifier_model);
```

**Comment by huningxin** [comment]
@ganwenyao , could you please investigate this. How can we use it in tutorials? Thanks.

**Comment by ganwenyao** [comment]
This is how I instantiated the classifier in openCV.js:
```js
let face_cascade = new cv.CascadeClassifier(), eye_cascade = new cv.CascadeClassifier();
let x = new XMLHttpRequest();
x.open("GET", "file:///home/ganwenyao/opencv/build_js/doc/doxygen/html/haarcascade_frontalface_default.xml", false);
x.send(null);
let fs = new cv.FileStorage();
fs.open(x.responseText, cv.FileStorage_READ + cv.FileStorage_MEMORY);
face_cascade.read(fs.getFirstTopLevelNode());
```
But Chrome warning : 
```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

**Comment by sajjadt** [comment]
We can load the file [asynchronously](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests).
```
x.open("GET", "path/to/haarcascade_frontalface_default.xml", true);
```

**Comment by huningxin** [comment]
@ganwenyao , would you able to try solution by @sajjadt ?

**Comment by ganwenyao** [comment]
I have tried it, but there are some errors. I will investigate it.

**Comment by huningxin** [comment]
Implement the asynchronous loading in https://github.com/opencv/opencv/pull/9713
