### ISSUE TITLE
Build with standard emscripten

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#14]
Currently it uses emscripten with patch: https://github.com/ucisysarch/opencvjs/blob/master/patch_emscripten_master.diff

**Comment by huningxin** [comment]
@sajjadt , could you please tell us which part of opencv.js depends on this patch? Thanks!

**Comment by sajjadt** [comment]
Two changes are made:
https://github.com/ucisysarch/opencvjs/blob/master/patch_emscripten_master.diff#L1
First modification to  Bind.h is to provide support for dynamic inheritance between C++ classes. We add an attribute for those cases and based on that proper cast (static_cast or dynamic_cast) will be performed.

https://github.com/ucisysarch/opencvjs/blob/master/patch_emscripten_master.diff#L57
Second change is to fix a bug in embind.js which skips to register number of function parameters. In case of having function overloading, this information will be used to select the right function based on number of parameters.

**Comment by huningxin** [comment]
@sajjadt , thanks for explanation! Would you please upstream these fixes to emscripten? So opencv.js will use emscripten without patch.

**Comment by sajjadt** [comment]
I was not able to reproduce the second error in minimal tests; It seems something goes wrong with that previous build approach. I tested our new build script with un-patched Emscripten and there was no problem there. This issue does not affect us anymore, but I will continue investigation separately.

**Comment by huningxin** [comment]
I verified un-patched emscripten can build and pass the tests.

@sajjadt , do you think we can close this issue?

**Comment by huningxin** [comment]
As agreed in the sync meeting, we close this issue. @sajjadt , please paste link the PR to emscripten here for reference when it is ready. Thanks!
