### ISSUE TITLE
Apply OpenCV coding style

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#155]

**Comment by pancx** [comment]
Js code style https://google.github.io/styleguide/

**Comment by sajjadt** [comment]
[OpenCV preferred style](https://github.com/opencv/opencv/wiki/Coding_Style_Guide)

**Comment by pancx** [comment]
The opencv coding style guide is more about C++. But I find some gaps need to resolve.
- [ ] If the test needs some data, put it to the separate [top-level directory](https://github.com/opencv/opencv_extra/tree/master/testdata)
- [ ] Every source file, except for the samples, starts with BSD-compatible license, [template](https://github.com/opencv/opencv/blob/master/LICENSE)

**Comment by sajjadt** [comment]
Good point about the videos. For tutorials, all the files (they are only images) in the main repo, however if we have (or eventually will have) large videos it might be a better idea to keep them in a separate repo. We have to see how many videos are needed in the long term.

Have we used licensed material beside OpenCV.js original source codes?
