### ISSUE TITLE
[Mat] We don't need "at" function for Mat

### ISSUE THREAD

**Issue by ganwenyao** [huningxin/opencv#158]
at:
````js
let pixel = src.getUcharAt(y, x * src.channels());
````
ptr:
````js
let pixel = src.getUcharPtr(y, x)[0];
````
We don't need "at" function because "ptr" can do all the things including what "at" can do. 
Maybe we need a better function name for "ptr".

**Comment by huningxin** [comment]
Let's align to OpenCV C++ APIs which have `at` and `ptr`.
