### ISSUE TITLE
JS tutorial for core

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#17]

**Comment by remember08** [comment]
write a list of contents in the Core Functionality Modules.

- mat in opencv.js
- how to scan images
- mask operations of matrices
- core operations with images
- arithmetics operations with images

**Comment by huningxin** [comment]
Good list. Please file issue for each item and link them here. Thanks!

**Comment by huningxin** [comment]
- [x] mat in opencv.js
- [x] how to scan images
- [x] mask operations of matrices
- [x] core operations with images
- [x] arithmetic operations with images

**Comment by huningxin** [comment]
Add @pancx @ganwenyao to this task.

**Comment by huningxin** [comment]
fixed by https://github.com/huningxin/opencv/pull/181. Thanks much!
