### ISSUE TITLE
JS tutorial for image processing - part 1

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#18]

**Comment by ganwenyao** [comment]
In Opencv-Python tutorials,  there are 16 sections in image processing:
- [x] Changing Colorspaces
- [x] Geometric Transformations of Images
- [x] Image Thresholding
- [x] Smoothing Images
- [x] Morphological Transformations
- [x] Image Gradients
- [x] Canny Edge Detection
- [x] Image Pyramids
- [x] Contours in OpenCV
- [ ] Histograms in OpenCV
- [ ] Image Transforms in OpenCV
- [ ] Template Matching
- [ ] Hough Line Transform
- [ ] Hough Circle Transform
- [ ] Image Segmentation with Watershed Algorithm
- [ ] Interactive Foreground Extraction using GrabCut Algorithm

**Comment by ganwenyao** [comment]
Functions in image process (keep updating):
https://docs.google.com/a/intel.com/spreadsheets/d/17brxaSvp88sEXCZjkYxI88OOXGQW_9Mwsw2D0abRi9o/edit?usp=sharing

**Comment by huningxin** [comment]
This part is covered by https://github.com/huningxin/opencv/pull/80. Close this one. Follow up the remaining tutorials in #113
