### ISSUE TITLE
Build without Unnecessary  Components

### ISSUE THREAD

**Issue by sajjadt** [huningxin/opencv#186]
These OpenCV components need to be explicitly disabled.
OpenCL
Java
Python
IPP
Pthreads
OpenEXR
trace
ffmpeg

also some modules are not supported and don't need to be built. e.g.
dnn
shapes
calib3d

aslo, maybe these two as well:
TIFF
WEBP

**Comment by huningxin** [comment]
opencv.js target should only depend on:
* core
* imgproc
* video
* objdetect
