### ISSUE TITLE
[Demo1] Find QR Code

### ISSUE THREAD

**Issue by ganwenyao** [huningxin/opencv#187]
* My github repository:
https://github.com/ganwenyao/openCV_demo1_findQrCode
* Demo websites:
https://ganwenyao.github.io/openCV_demo1_findQrCode/findQrCode.html
https://ganwenyao.github.io/openCV_demo1_findQrCode/findQrCodeCamera.html

**Comment by ganwenyao** [comment]
QR code decoder is tedious and sophisticated. We may need some Open Source QR Code Library to decode it.

**Comment by huningxin** [comment]
Thanks for the demo!
