### ISSUE TITLE
[Demo2] Haze Remove

### ISSUE THREAD

**Issue by ganwenyao** [huningxin/opencv#188]
This demo refers to the paper:  _Single Image Haze Removal Using Dark Channel Prior_
My github repository:
https://github.com/ganwenyao/openCV_demo2_findQrCodehazeRemove
Demo website:
https://ganwenyao.github.io/openCV_demo2_findQrCodehazeRemove/hazeRemove.html

**Comment by huningxin** [comment]
Thanks!
