### ISSUE TITLE
Final submission report

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#191]
According to https://developers.google.com/open-source/gsoc/help/work-product, it requires:
"
Create a blog post or web page or public GitHub gist that describes the work you've done and links to the commits you've made and repositories you've worked on. If there is still work to be done on the project, include that too. You can also share highlights or challenging pieces.
"

**Comment by pancx** [comment]
Just a draft for final report https://gist.github.com/pancx/2778b72090782b6e5b47af13a32b0d7d 
@sajjadt Please have a look.

**Comment by sajjadt** [comment]
@pancx I think it needs to be explained a bit more. Look at these examples from previous GSoC projects. These are shared as good examples on GSoC mailing list.
 
https://gist.github.com/vaidap/83ff59865f199e75ccd1b06607d07bd5
https://dhavalkapil.com/blogs/Elasticsearch-Lua-GSOC-2016/

You can use content from opencv.js tutorial. Once you have a draft I can do a review pass.

**Comment by pancx** [comment]
Report updated @sajjadt . The link is settled.
https://gist.github.com/pancx/2778b72090782b6e5b47af13a32b0d7d

**Comment by sajjadt** [comment]
@pancx Thanks, I did an [edit](https://gist.github.com/sajjadt/51a985607f3cdc18f05a58ef362af9ba).

**Comment by pancx** [comment]
@sajjadt Thanks a lot!
