### ISSUE TITLE
Make short video

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#193]
We also need to make a short video,  see:
* https://www.youtube.com/watch?v=Z3mkbYO2o4k
* https://www.youtube.com/watch?v=Akeh36-VMTU

**Comment by pancx** [comment]
https://youtu.be/Iz6JPsW6jt0 
@sajjadt @huningxin

**Comment by huningxin** [comment]
Looks very good! Thanks!

**Comment by pancx** [comment]
Video updated https://youtu.be/lx5btJJcvek

**Comment by sajjadt** [comment]
Awesome!
