### ISSUE TITLE
Test opencv_js.js against https://github.com/ucisysarch/opencvjs/tree/master/test

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#2]

**Comment by pancx** [comment]
move to #4

**Comment by huningxin** [comment]
@pancx , please log what you did and the results of your testing here for record. Thanks!

**Comment by pancx** [comment]
First, copy the test files from ucisysarch/opencvjs/test. 
Then modify the files to test opencv_js.js. 
a. rename cv.js to opencv_js.js
b. add window.cv = cv(Module);
c. delete script async attribute.
d. modify data file's path.
Finally, all tests passed.

**Comment by huningxin** [comment]
Looks good. Thanks!
