### ISSUE TITLE
JS tutorial for video analysis

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#21]

**Comment by pancx** [comment]
In Opencv-Python tutorials, the section of Video Analysis contains three tutorials, Meanshift and Camshift, Optical Flow, Background Subtraction. 
Functions mainly included, 
- cv.meanShift
- cv.CamShift
- cv.calcOpticalFlowPyrLK
- cv.calcOpticalFlowFarneback
- cv.createBackgroundSubtractorMOG2 (not exposed now)
- BackgroundSubtractor.apply
- cv.createBackgroundSubtractorGMG (no need)

In addition, we need to implement video input & output and its tutorial.

**Comment by pancx** [comment]
We need four tutorials for Video Analysis

- [x] Video input & output - use WebRTC #58 
- [x] Meanshift and Camshift - cv.meanShift, cv.CamShift
- [x] Optical Flow - cv.calcOpticalFlowPyrLK, cv.calcOpticalFlowFarneback
- [x] Background Subtraction - cv.BackgroundSubtractorMOG2, BackgroundSubtractor.apply

**Comment by huningxin** [comment]
Good list. Please file issue for each item and link them in the list. Thanks!

**Comment by huningxin** [comment]
We finished video io tutorials in M4, postpone this one to M5.

**Comment by pancx** [comment]
In OpenCV-Python tutorials, there are three background subtraction methods,
1. BackgroundSubtractorMOG
2. BackgroundSubtractorMOG2
3. BackgroundSubtractorGMG

1 and 3 have been not available in native opencv.
So, I will implement 2 only in the tutorial.

**Comment by pancx** [comment]
Code demos
- [x] Meanshift
- [x] Camshift
- [x] Optical Flow - cv.calcOpticalFlowPyrLK #119 need fixing
- [x] Optical Flow - cv.calcOpticalFlowFarneback
- [x] cv.BackgroundSubtractorMOG2

**Comment by huningxin** [comment]
This is closed by https://github.com/huningxin/opencv/pull/142. Nice job!
