### ISSUE TITLE
Experiment ORB_SLAM JavaScript support

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#211]
https://github.com/raulmur/ORB_SLAM2

**Comment by pancx** [comment]
@huningxin I need your work for reference.

**Comment by huningxin** [comment]
I pushed my work to https://github.com/huningxin/opencv/tree/orbslam2. At there, I integrate orbslam2 as a module into opencv source tree.

**Comment by pancx** [comment]
@huningxin Thanks. I will have a try.
