### ISSUE TITLE
OpenCV.JS API V2

### ISSUE THREAD

**Issue by sajjadt** [huningxin/opencv#23]
We need a new API with modern JavaScript in mind. The existing API is tied to the original C++ API which is not ideal for JS world. Consider the following inspiring example taken from the tests. 

```js
  var aa = 1,
        source = new cv.MatVector(),
        channels = new cv.IntVector(),
        histSize = new cv.IntVector(),
        ranges = new cv.FloatVector();

  var vec1 = new cv.Mat.ones([20, 20], cv.CV_8UC1);
  source.push_back(vec1);
  channels.push_back(0);
  histSize.push_back(256);
  ranges.push_back(0); ranges.push_back(256);

  let hist = new cv.Mat();
  let mask = new cv.Mat();
  cv.calcHist(source, channels, mask, hist, histSize, ranges, false);
```

Looking at ```cv.calcHist``` function, we can observe several issues.

1. It is based on C++ syntax. At the very least Python API is preferred, since I assume it is the most popular version. For comparison, here is the Python signature for ```calcHist``` function
```py
cv2.calcHist(images, channels, mask, histSize, ranges[, hist[, accumulate]]) → hist
```
2. Usage of ```std::Vector``` in JavaScript. So JS programmers are expected to know about C++ STL.
3. Output parameters is being passed by reference which again is not too common in JS.
4. Not supporting default parameters
5. ~~Using ```null``` variable instead of empty Mat object is preferred.~~

Using new API same code can be re-written as follows.

```js
  var vec1 = new cv.Mat.ones([20, 20], cv.CV_8UC1),
        sources = [vec1],
        channels = [0, 1, 2], 
        histSize = [256, 256, 256],
        mask = new cv.Mat(),
        ranges = [0, 256];

  var hist = cv.calcHist(source, channels, mask, histSize, ranges);
```

**Comment by huningxin** [comment]
I had an investigation, it shows we can use `std::vector<T> vecFromJSArray(val v)` (https://kripken.github.io/emscripten-site/docs/api_reference/val.h.html) to implement this feature.

I manually modified the wrapper of `calcHist` in `bindings.cpp` to
```
void calcHist_wrapper(const emscripten::val& arg1, const emscripten::val& arg2, const cv::Mat& arg3, cv::Mat& arg4, const emscripten::val& arg5, const emscripten::val& arg6, bool arg7) {
  return cv::calcHist(emscripten::vecFromJSArray<cv::Mat>(arg1), emscripten::vecFromJSArray<int>(arg2), arg3, arg4, emscripten::vecFromJSArray<int>(arg5), emscripten::vecFromJSArray<float>(arg6), arg7);
}
```

It passes the code
```
var vec1 = new cv.Mat.ones([20, 20], cv.CV_8UC1);
var sources = [vec1];
var channels = [0] 
var histSize = [256];
var ranges = [0, 256];
var hist = new cv.Mat();
var mask = new cv.Mat();
cv.calcHist(sources, channels, mask, hist, histSize, ranges, false);
```

@sajjadt , please take a look. It is OK. I am going to modify the `embindgen.py` to support it.

**Comment by sajjadt** [comment]
Looks pretty good to me!

**Comment by huningxin** [comment]
#45 fixes item 2 of the proposal. Please take a look.

**Comment by sajjadt** [comment]
Here is a way to support default parameters and returning by value instead of reference. For this we need to create a wrapper for each function with a certain signature.

#### Supporting default parameters
We can use ```emscripten::val``` to support this feature as they can contain different types of values including undefined values.

Consider this function:
```c++
void accumulate(char a, short b = 1, float c=2.0, int d = 3, double e=4.0) {
     int_prop += ( a + (int)b + int(c) + int(d) + int(e) );
  }
```
A binding to support default parameters would be like this:
```c++
void accumulateWrapper(MyClass& obj, const emscripten::val& a, const emscripten::val& b, const emscripten::val& c, const  emscripten::val& d, const emscripten::val& e) {
  obj.accumulate(a.as<char>(), b.isUndefined()?1:b.as<short>(), c.isUndefined()?2.0:c.as<float>(), d.isUndefined()?3:d.as<int>(), e.isUndefined()?4.0:e.as<double>());
}
```
Python wrapper generator already keeps track of default parameters and can be used to generate this binding. However we need to apply one small change to Embind as it checks the number of parameters and raises an error if not enough parameters are provided. It can be bypassed by commenting out the following line in [embind.js](https://github.com/kripken/emscripten/blob/master/src/embind/embind.js).

```js
 var invokerFnBody =
        "return function "+makeLegalFunctionName(humanName)+"("+argsList+") {\n" +
        "if (arguments.length !== "+(argCount - 2)+") {\n" +
        //    "throwBindingError('function "+humanName+" called with ' + arguments.length + ' arguments, expected "+(argCount - 2)+" args!');\n" +
        "}\n";
```



#### Returning values instead of passing references
We can define another wrapper around original function to fulfill this task. I have provided an example.


Here is the sample code including binding code. It can be compiled with the following command.
```sh
em++ main.cpp --bind -o main.htm
```
Here is a sample code to test it.

```js
var a = new Module.MyClass();
a.accumulate(-1);  // -1+1+2+3+4
a.accumulate(-1, 3); //-1+3+2+3+4
a.accumulate(-1, 3, 4.4); // -1+3+4.4+3+4
```

```c++
#include <iostream>
#include <emscripten/bind.h>
using namespace emscripten;
class MyClass {
public:
  MyClass(){}
  int getIntProp() const { return int_prop; }
  void setIntProp(int int_prop_) { int_prop = int_prop_; }
  void accumulate(char a, short b = 1, float c=2.0, int d = 3, double e=4.0) {
     int_prop += ( a + (int)b + int(c) + int(d) + int(e) );
  }

private:
  int int_prop;
};

// Wrapper function for MyClass::accumulate
void accumulateWrapper(MyClass& obj, const emscripten::val& a, const emscripten::val& b, const emscripten::val& c, const  emscripten::val& d, const emscripten::val& e) {
  obj.accumulate(a.as<char>(), b.isUndefined()?1:b.as<short>(), c.isUndefined()?2.0:c.as<float>(), d.isUndefined()?3:d.as<int>(), e.isUndefined()?4.0:e.as<double>());
}

// Clone function, simply make a copy, can use copy constructor etc
void cloneMyClass(const MyClass& in, MyClass& out) {
  out.setIntProp(in.getIntProp());
}
// Wrapper function for clone function by returning a copy
MyClass cloneWrapper(const MyClass& in) {
  MyClass out;
  cloneMyClass(in, out);
  return out;
}

EMSCRIPTEN_BINDINGS(bindings) {
  class_<MyClass>("MyClass")
    .constructor<>()
    .function("accumulate", &accumulateWrapper)
    .property("int_prop", &MyClass::getIntProp, &MyClass::setIntProp)
    ;
  function("clone", &cloneWrapper);
}
```

**Comment by sajjadt** [comment]
@huningxin What do you think?

**Comment by huningxin** [comment]
Thanks for sharing your thoughts @sajjadt ! It is very helpful.

For "Supporting default parameters", can we use function overloading with arguments count? Just like https://github.com/kripken/emscripten/issues/604 and your investigation, doing it at runtime is not supported by embind and may introduce some performance cost.

I tried modified `cv.normalize` like:

wrapper code:
```c++
void normalize_wrapper(const cv::Mat& arg1, cv::Mat& arg2, double arg3, double arg4, int arg5, int arg6, const cv::Mat& arg7) {
    return cv::normalize(arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

void normalize_wrapper1(const cv::Mat& arg1, cv::Mat& arg2) {
    return cv::normalize(arg1, arg2);
}

void normalize_wrapper2(const cv::Mat& arg1, cv::Mat& arg2, double arg3) {
    return cv::normalize(arg1, arg2, arg3);
}

void normalize_wrapper3(const cv::Mat& arg1, cv::Mat& arg2, double arg3, double arg4) {
    return cv::normalize(arg1, arg2, arg3, arg4);
}

void normalize_wrapper4(const cv::Mat& arg1, cv::Mat& arg2, double arg3, double arg4, int arg5) {
    return cv::normalize(arg1, arg2, arg3, arg4, arg5);
}

void normalize_wrapper5(const cv::Mat& arg1, cv::Mat& arg2, double arg3, double arg4, int arg5, int arg6) {
    return cv::normalize(arg1, arg2, arg3, arg4, arg5, arg6);
}
```
binding code:
```c++
function("normalize", select_overload<void(const cv::Mat&, cv::Mat&, double, double, int, int, const cv::Mat&)>(&Wrappers::normalize_wrapper));

function("normalize", select_overload<void(const cv::Mat&, cv::Mat&)>(&Wrappers::normalize_wrapper1));

function("normalize", select_overload<void(const cv::Mat&, cv::Mat&, double)>(&Wrappers::normalize_wrapper2));

function("normalize", select_overload<void(const cv::Mat&, cv::Mat&, double, double)>(&Wrappers::normalize_wrapper3));

function("normalize", select_overload<void(const cv::Mat&, cv::Mat&, double, double, int)>(&Wrappers::normalize_wrapper4));

function("normalize", select_overload<void(const cv::Mat&, cv::Mat&, double, double, int, int)>(&Wrappers::normalize_wrapper5));
```

JS can be written as:
```js
var a = new cv.Mat();
var b = new cv.Mat();
cv.normalize(); // Exception
cv.normalize(a, b); // OK
cv.normalize(a, b, 1); // OK
cv.normalize(a, b, 1, 2); // OK
cv.normalize(a, b, 1, 2, cv.NormTypes.NORM_L1.value); // OK
cv.normalize(a, b, 1, 2, cv.NormTypes.NORM_L1.value, -1, a); // OK
cv.normalize(a, b, 1, 2, cv.NormTypes.NORM_L1.value, -1, a, b); // Exception
```

What do you think? If it is OK, I can make a stab.

**Comment by sajjadt** [comment]
This is a nice way to do it.

**Comment by huningxin** [comment]
Move the default parameter feature to M4.

**Comment by huningxin** [comment]
When using JS array for Mat `[mat]` developers need to take care the life time of each Mat in the array. They need to delete each Mat in the array explicitly. However, when using `MatVector`, developers only need to delete the `MatVector` which will delete all the inside it.

For this reason, I would suggest we keep `MatVector`.

**Comment by huningxin** [comment]
For "Returning values instead of passing references", I would suggest to keep the passing references for this version of API. The reasons:
1. extra performance costs for objects creation, especially for array.
2. for multiple returning values, need to create one more array or object as container
3. returning values by passing references is desired by Web developers for performance reason, e.g. minimum GC impact in rendering loop.
4. aligns to OpenCV C++ API signature, so no need to create specific API reference manual for JS.

@sajjadt , WDYT?

**Comment by sajjadt** [comment]
Good point about MatVector. We can keep it, though since programmers need to delete every mat object, it is not too much asking them to remove all mats within a vector as well!

I agree about the performance. Plus, I'm not sure if we can support a case like this.
Consider this function with two parameters: one input and one output array. ```cv_func(InputArray in, InputArray out)```

if we call it this way ```cv_func(mat1, mat1)``` OpenCV will utilize the same mat instance and does in-place computation. This is not possible to achieve this way : ```mat1 = cv_func(mat1)```

**Comment by huningxin** [comment]
Got consensus with @sajjadt in sync meeting, close this issue.

**Comment by huningxin** [comment]
One clarification about `MatVector`: as `std::vector` employs the copy semantic, it means when push_back a mat into MatVector, MatVector will copy it and maintain the copy, so when deleting MatVector, it will only take care of the copies, developer still needs to delete the original mats. 

For example:
```js
let mat1 = new cv.Mat();
let mat2 = new cv.Mat();
let matVec = new cv.MatVector();
matVec.push_back(mat1);
matVec.push_back(mat2);
cv.Foo(matVec); // matVec as input parameter
matVect.delete();
mat2.delete();
mat1.delete();
```

However, when using MatVector to get some returning value, developer doesn't need to delete each copy. Say

```js
let matVec = new cv.MatVector();
cv.Foo(matVec); // matVec as output parameter
// return mats in matVec
matVec.delete();
```

Thanks @pancx  for remaindering this. CC @ganwenyao , you may need to know this for tutorials.
