### ISSUE TITLE
[Request] Is the script used for building your opencv.js in npm pkg available?

### ISSUE THREAD

**Issue by mjyc** [huningxin/opencv#245]
@huningxin , thank you for publishing a prebuilt opencv.js file as an [npm package](https://www.npmjs.com/package/opencv.js). 

Can you provide the script (or command) you used to build (https://www.npmjs.com/package/opencv.js)? 

I'm trying to extend the opencv.js npm pkg with the calib3d module so I made [the following changes](https://github.com/mjyc/opencv/tree/js3.4.5_calib3d) and compiled it by following [the instructions from the offical opencv website](https://docs.opencv.org/3.4.5/d4/da1/tutorial_js_setup.html).
When I loaded the opencv.js I built, it did not behave like the one in your opencv.js npm pkg.
For example, it required for me to wait until the compiled file is fully loaded ([the same issue is reported by others](https://dev.to/kjunichi/requireopencvjs-is-not-enough-for-using-opencvjs-8ff)), which is not the case for your opencv.js pkg. Also, some browsers could not load the library due to this error: `"Assertion failed: no binaryen method succeeded."`.

It'd be great if you can share the tips for building opencv.js that behaves like other js modules.

**Comment by mjyc** [comment]
Found an answer from http://answers.opencv.org/question/207288/how-can-i-compile-opencvjs-so-that-it-does-not-require-defining-the-onruntimeinitialized-field/?answer=207290#post-id-207290

**Comment by huningxin** [comment]
Thanks for sharing the answer!
