### ISSUE TITLE
[Investigation] JavaScript benchmark library

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#246]

**Comment by huningxin** [comment]
We need to investigate and select a suitable JavaScript benchmark library for OpenCV.js, for example [benchmark.js]. The solution of this issue would include:
1. the features of the library
2. a comparison with opencv native perf tool
3. a plan of how to integrate it into opencv.js

**Comment by Wenzhao-Xiang** [comment]
Seems we can use [Benchmark Suite](https://benchmarkjs.com/docs#Suite) API.

here's an outline of how a test is executed:
```js
For each benchmark in a suite:
    Fire event: Suite.onStart()
    For each benchmark:
        Fire event: Benchmark.onStart()
            For each sampled run
            Run unit once to check for errors
                setup()
                testfn()
                teardown()
            Run unit multiple times and measure results
                setup()
                for each Benchmark.count
                    testfn()
                teardown()
            Fire event: Benchmark.onCycle()
        Fire event: Benchmark.onComplete()
        Fire event: Suite.onCycle()
    Fire event: Suite.onComplete()
```

**Comment by huningxin** [comment]
benchmak.js looks like a good solution. Let's use it for initial OpenCV.js performance measurement. Thanks for the investigation.
