### ISSUE TITLE
Create the base of OpenCV.js benchmark

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#247]

**Comment by huningxin** [comment]
I happened to create a very initial tool ([js/test/perf.js](https://github.com/huningxin/opencv/blob/perf/modules/js/test/perf.js)) to measure OpenCV.js performance. With this tool, I measured four kernels of imgproc in OpenCV.js vs. native. The instructions are documented in [a doc](https://docs.google.com/document/d/1mJW632ZCWHXCuxLr_a8YhkGFsrLd2aBokpIc5eoJry8/edit?usp=sharing). The results is captured in [a spreadsheet](https://docs.google.com/spreadsheets/d/1qciPDHX75gRYhXGZFDBBkU90srNyMKAQW47oKmg7xCM/edit?usp=sharing).

It may help this task. Please take a look. @Wenzhao-Xiang .

**Comment by Wenzhao-Xiang** [comment]
Some performance data collected by using `Benchmark.js`:

=== GaussianBlur ===
elapsed time:8850 ms
mean time:4.153391787716161 ms
stddev time:0.31379444414825014 ms
GaussianBlur x 241 ops/sec ±1.30% (129 runs sampled)
=== cvtColor ===
elapsed time:8797 ms
mean time:0.5263658874033388 ms
stddev time:0.021411419599429788 ms
cvtColor x 1,900 ops/sec ±0.68% (137 runs sampled)
=== threshold ===
elapsed time:8775 ms
mean time:0.25882412385726333 ms
stddev time:0.018852328617259655 ms
threshold x 3,864 ops/sec ±1.24% (133 runs sampled)
=== integral2 ===
elapsed time:8872 ms
mean time:0.8818490609382015 ms
stddev time:0.056310464083636554 ms
integral2 x 1,134 ops/sec ±1.08% (134 runs sampled)

I'm now working with `setup/teardown` of `Benchmark.js`

**Comment by Wenzhao-Xiang** [comment]
Seems we need require `opencv.js` again in `setup/tearown` function, or `cv` can't be found by them.
According to https://github.com/bestiejs/benchmark.js/issues/94#issuecomment-110431216, it needs a workaround for using `require` in benchmark.js . I modified the `benchmark.js` and now it works.

And According to @terfendail 's feedback, I will start with `cvtColor` to create the base of OpenCV.js benchmark.

**Comment by huningxin** [comment]
> Seems we need require `opencv.js` again in `setup/tearown` function, or `cv` can't be found by them.

You may use `global.cv = cv;` to avoid the workaround and requiring `cv` many times. 
And please also handle the error loudly by adding `error` handler.

I've put some comments into your commit: https://github.com/Wenzhao-Xiang/opencv/commit/ca7bafc95a867b44d72de3f0f863e24c71572720. Please take a look.

**Comment by Wenzhao-Xiang** [comment]
Got it! Thanks!

**Comment by huningxin** [comment]
closed by https://github.com/huningxin/opencv/pull/262
