### ISSUE TITLE
Add imgproc kernels into OpenCV.js benchmark

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#248]

**Comment by Wenzhao-Xiang** [comment]
According to https://github.com/huningxin/opencv/issues/260#issuecomment-500885482, first implemented cvtColor of all cases compared with opencv native. The total number of perf test cases is 511, and seems it may take a long time to test all the cases. Testing on my machine(Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz, Chrome version 74.0.3729.157), it cost about 50 minutes(Native is 15 min).
Here is the commit 9e619e8bd149e5d89cc4eeb4c8ff870a992055ab

**Comment by huningxin** [comment]
We have the initial two imgproc kernels (cvtColor and resize) in the benchmark. Close this one. If we need more, please open corresponding issue.
