### ISSUE TITLE
[Meta] optimize performance by WASM SIMD

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#257]

**Comment by Wenzhao-Xiang** [comment]
First, we should try to build opencv.js with emscripten upstream backend since now only emscripten LLVM upstream backend support WASM SIMD instructions. 
However, there are now many warnings and errors like `undefined symbol: g$_ZTVNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE` in the process now. I set "-s ERROR_ON_UNDEFINED_SYMBOLS=0" to ignore these errors and succeed to build a version of `opencv.js`, but it doesn't work at all.

**Comment by Wenzhao-Xiang** [comment]
file a upstream bug here: https://github.com/emscripten-core/emscripten/issues/8986

**Comment by Wenzhao-Xiang** [comment]
@huningxin @terfendail 
Step to reproduce:
First, install the latest version of emsdk
1. `git clone https://github.com/emscripten-core/emsdk.git`
2. `git pull`
3. `./emsdk install latest-upstream`
4. `./emsdk activate latest-upstream`

Second, build opencv.js with LLVM upstream backend:
1. `git clone https://github.com/huningxin/opencv.git`
2. `cd opencv/`
3. run `python ./platforms/js/build_js.py ${build_dir} --build_wasm --build_test --emscripten_dir="${your_emsdk_path}/emsdk/upstream/emscripten"`

**Comment by Wenzhao-Xiang** [comment]
I have a primary investigation of SIMD instructions used in cvtColor:
`v_load_deinterleave, v_store_interleave, v_reinterpret_as_u16, v_pack , swap, v_expand , v_store, vx_load_low, v_expand_low, v_zip, v_reinterpret_as_s16, v_reinterpret_as_u32, v_dotprod, v_store_low, v_fma, v_add_wrap, v_mul_expand, v_cvt_f32, v_trunc, v_select, vx_cleanup, vx_load, vx_setall_${type}, vx_setzero_${type}, vx_load_low, v_max, v_min, v_store_aligned, v_pack_u, v_abs, v_muladd, v_round, vx_lut, vx_load_aligned, vx_load_expand, v_sub_wrap `

I'm trying to use WASM SIMD instruction to map the functions of OpenCV Universal Intrinsics, but don't if them work correctly. 
@terfendail Do you have any methods to do the unit test, for example, test `v_mul_expand`?

**Comment by terfendail** [comment]
There is a set of unit test related to universal intrinsics.
Most of the tests code is located in `opencv/modules/core/test/test_intrin.cpp` and some specifications could be found in `opencv/modules/core/test/test_intrin_utils.hpp`.
As far as I understand it's impossible to just reuse core module accuracy tests, but I hope this code could be a good starting point

**Comment by terfendail** [comment]
Also there is a plain c++ implementation for all available universal intrinsics in `opencv/modules/core/include/opencv2/core/hal/intrin_cpp.hpp` that could also be used as a reference.

**Comment by Wenzhao-Xiang** [comment]
@terfendail Got it, Thanks!

**Comment by Wenzhao-Xiang** [comment]
Some updates can see in this branch: https://github.com/Wenzhao-Xiang/opencv/tree/opencvjs_simd
@huningxin @terfendail

**Comment by huningxin** [comment]
As synced on Monday, we need to:
1. pass the test_intrin.cpp
2. fallback to c++ impl if no WASM support

**Comment by huningxin** [comment]
> 1. pass the test_intrin.cpp

To enable `test_intrin.cpp` in WASM build, it requires to build opencv tests that depend on many other modules, e.g. `videocodec`, `videoio`, `highgui` etc. And there are dependency issues to build those modules by emscripten. It seems not straight-forward to solve these dependency issues quickly in this GSoC project.

My proposal is to just expose intrin tests (e.g. [`test_hal_intrin_float32`](https://github.com/huningxin/opencv/blob/gsoc_2019/modules/core/test/test_intrin_utils.hpp#L18)) in JS binding (OpenCV.js) under a build option (e.g. `--test_wasm_intrins`). Then we can test them in browser console. I have a quick prototype that it works with C++ implementation. If this proposal looks good, I can send a PR to implement it. 

@terfendail @Wenzhao-Xiang , WDYT?

**Comment by huningxin** [comment]
> 2. fallback to c++ impl if no WASM support

Re-use c++ impl in WASM backend if no WASM support.

**Comment by huningxin** [comment]
> If this proposal looks good, I can send a PR to implement it.

synced with @terfendail @Wenzhao-Xiang , we go with this approach. I will send the PR.

**Comment by Wenzhao-Xiang** [comment]
Some update in branch https://github.com/Wenzhao-Xiang/opencv/tree/opencvjs_simd:
1. support all the kernels of wasm intrin 
2. now still two kernels `v_signmask(f32)` and `v_check_any(f32)` can't pass the test
3. test `resize` with benchmark, it's 5x slower than scalar version

For try, please run 
```sh
python ./platforms/js/build_js.py build_simd --build_wasm --build_test --build_perf --simd128 --build_wasm_intrin_test
```
@huningxin @terfendail

**Comment by Wenzhao-Xiang** [comment]
I investigated the SIMD instructions used in `resize`:
```
vx_setall_u8, vx_setall_u16, vx_setall_s16, vx_setall_u32, vx_setall_s32, vx_setall_u64, vx_setall_f32, 
v_reinterpret_as_u8, v_reinterpret_as_s8, v_reinterpret_as_u16, v_reinterpret_as_s16, v_reinterpret_as_u32, v_reinterpret_as_u64, 
v_pack_triplets, v_interleave_pairs, v_interleave_quads, v_store_interleave, v_load_deinterleave, 
v_store, v_store_low, vx_load, vx_load_aligned, vx_load_expand(v_load_expand), 
v_expand, 
vx_lut_pairs, vx_lut_quads, 
v_zip, v_recombine, 
v_pack, v_pack_u, v_pack_u_store, v_rshr_pack_u, v_rshr_pack, v_rshr_pack_u_store, v_rshr_pack_store, 
v_dotprod, 
v_add_wrap, v_muladd, v_mul_hi, 
v_round, 
v_rotate_left, 
v_cvt_f32, 
```
Among these kernels, `v_pack, v_pack_u, v_pack_u_store, v_rshr_pack_u, v_rshr_pack, v_rshr_pack_u_store` fall back to c++ implementation, which may cause performance issue. And also, I use lots of `wasm_v8x16_shuffle` to simulate other operations, which may also seem like a hidden danger.

**Comment by Wenzhao-Xiang** [comment]
Did some test. Modify the `pack` kernel code as the following to see if the "wasm_v128_store" is the root cause of performance issue: 
```c++
#define OPENCV_HAL_IMPL_C_PACK(_Tpvec, _Tp, _Tpnvec, _Tpn, pack_suffix, cast) \
inline _Tpnvec v_##pack_suffix(const _Tpvec& a, const _Tpvec& b) \
{ \
    _Tp p[_Tpnvec::nlanes] = {2}; \
    /*wasm_v128_store(p, a.val); \
    wasm_v128_store(p+_Tpvec::nlanes, b.val);*/ \
    _Tpn c[_Tpnvec::nlanes]; \
    for( int i = 0; i < _Tpnvec::nlanes; i++ ) \
    { \
        c[i] = cast<_Tpn>(p[i]); \
    } \
    return _Tpnvec(wasm_v128_load(c)); \
}
```
After that, the performance of `resize` change from 25.94ms to 1.68ms, and also `cvtcolor` can be tested normally. Therefore, I think fall back implementation may be the main cause of this performance issue. I will next think about how to implement `pack` with wasm intrin.
@huningxin @terfendail

**Comment by huningxin** [comment]
I put together a PR https://github.com/huningxin/opencv/pull/281 that support the `simd` build option and re-use `intrin_cpp.hpp` as the base (fallback) of `intrin_wasm.hpp`. It can pass the intrin tests and replicate the (lower) performance as @Wenzhao-Xiang found.

I would propose that we use this as a base impl and @Wenzhao-Xiang can add the optimized implementation on top of that.

WDYT?

**Comment by Wenzhao-Xiang** [comment]
Sounds great. @huningxin 
On the other hand, I tried to optimize the `PACK` with wasm intrin, however, performance still didn't have big improvement. For example, for `resize(CV_8UC4,1280x720,640x480)`, time changed from about `25ms` to `20ms` (however, scalar version is about 5ms).

**Comment by huningxin** [comment]
> I would propose that we use this as a base impl and @Wenzhao-Xiang can add the optimized implementation on top of that.

Open https://github.com/huningxin/opencv/pull/282 for that. Please take a look.

**Comment by huningxin** [comment]
@Wenzhao-Xiang , one thing we need to take care is current code opens the "__wasm_unimplemented_simd128__" by default. That would be dangerous. Please make the code can work without this flag. I will open an issue for that.

**Comment by huningxin** [comment]
Let's close it.
