### ISSUE TITLE
Initial performance data of WASM and native

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#258]
Based on https://github.com/huningxin/opencv/issues/247 and [opencv perf tests](https://github.com/opencv/opencv/wiki/HowToUsePerfTests), please collect the initial performance data of WASM and native. It depends on the [selected kernels](https://github.com/huningxin/opencv/issues/260) and [native opencv build configurations](https://github.com/huningxin/opencv/issues/259), e.g.:
1. WASM (scalar) vs. native (scalar)
2. WASM (scalar) vs. native (threads)
3. WASM (scalar) vs. native (SIMD128/256)
4. WASM (scalar) vs. native (threads + SIMD)

**Comment by Wenzhao-Xiang** [comment]
Collect some performance data here.
https://docs.google.com/spreadsheets/d/17TS4wBDuKUr2aN_dOPlsGDX_7Zh8_XlUU3ownv3VZHs/edit?usp=sharing

According to the data, WASM(scalar) is about 30% slower than Native(scalar), and Native(threads+SIMD) is about 10x faster than Native(scalar). 
Please help take a look.
@huningxin @terfendail

**Comment by huningxin** [comment]
Good progress. Thanks @Wenzhao-Xiang . In your table, are you able to provide the command line (tool & options) for each data? It would help others to reproduce it on their machines.

**Comment by Wenzhao-Xiang** [comment]
Thanks! Updated it!

**Comment by Wenzhao-Xiang** [comment]
Will add another version of WASM performance data based on browser after #263 fixed.

**Comment by huningxin** [comment]
We have the initial data even with WASM (threads). Close this one. We may need to update the table with WASM (SIMD) and WASM(threads+SIMD).
