### ISSUE TITLE
Native OpenCV optimization build configurations

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#259]
This wiki page [CPU optimizations build options](https://github.com/opencv/opencv/wiki/CPU-optimizations-build-options) might be useful.

@terfendail, please provide your inputs. Thanks.

**Comment by terfendail** [comment]
Unfortunately there is no dedicated flag to disable parallel processing during compilation. It's possible to disable the option in the code by undefining of `CV_PARALLEL_FRAMEWORK` in `modules/core/src/parallel.cpp`.
However it's possible to dynamically disable parallel execution during collection of performance results by using `--perf_threads=1` flag. E.g. `./bin/opencv_perf_core --perf_threads=1`

Regarding SIMD there are a plenty of options. It's possible to disable all optimizations in the code by enabling of `CV_DISABLE_OPTIMIZATION` cmake parameter(which is OFF by default).
It's possible to disable usage of universal intrinsics only by disabling of `CV_ENABLE_INTRINSICS` cmake parameter(which is on by default). Also it's possible to disable intrinsics by setting of `CPU_BASELINE` and `CPU_DISPATCH` to empty values. Such configuration will disable non-intrinsics platform dependent optimizations as well.

**Comment by Wenzhao-Xiang** [comment]
Thanks for the inputs! I will try with these configurations!

**Comment by huningxin** [comment]
Close this one.
