### ISSUE TITLE
Select kernels for OpenCV.js optimization

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#260]
@terfendail, please help scope the kernels for OpenCV.js optimization.

**Comment by terfendail** [comment]
I've discussed the list of functions to optimize with the OpenCV team and get the following list(in order of precedence):
1.	cvtColor(especially BGR2GRAY, YUV2BGR, BGR2YUV)
2.	resize(especially LINEAR_BITEXACT/LINEAR)
3.	Sobel
4.	Scharr
5.	gaussianBlur
6.	blur
7.	medianBlur
8.	erode
9.	dilate
10.	morphologyEx
11.	remap
12.	warpAffine
13.	warpPerspective
14.	pyrDown
15.	buildPyramyd

I think it make sense to estimate necessary efforts per function and decide on reasonable subset to focus on during GSoC2019

**Comment by huningxin** [comment]
Close this issue as we got the list.
