### ISSUE TITLE
Enable performance test building option

### ISSUE THREAD

**Issue by Wenzhao-Xiang** [huningxin/opencv#266]
Add an extra building option for opencv.js performance test.

**Comment by Wenzhao-Xiang** [comment]
Now, the test file and benchmark file have some conflicts. Maybe we should have a discussion about the file structure.
@huningxin @terfendail

**Comment by huningxin** [comment]
@Wenzhao-Xiang , thanks for raising up this issue. Could you please elaborate the conflicts? And do you have any proposals to fix the conflicts?

**Comment by huningxin** [comment]
@Wenzhao-Xiang , does it work by copying [`perf`](https://github.com/huningxin/opencv/tree/gsoc_2019/modules/js/perf) directory into `bin`.
