### ISSUE TITLE
Loader to detect platform features and load according OpenCV.js

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#268]
OpenCV.js would have multiple builds for different browser features: ASM.js vs. WASM, threads vs. no threads, SIMD vs. no SIMD. And the browser may or may not support each of these features. So it would be ideal to handle the platform feature detection and load according OpenCV.js for developer.

**Comment by lionkunonly** [comment]
@huningxin  Hi, Ningxin. I am not sure what should I do to implement such a loader. Could you give some suggestions or some reference?

**Comment by huningxin** [comment]
A reference: https://github.com/GoogleChromeLabs/wasm-feature-detect

**Comment by lionkunonly** [comment]
Thanks for your suggestions. Let me check my plan for the implementation. 

Firstly, I think I need to build multiple versions of the `opencv.js`. For example, if the user builds the `opencv.js` with command `--simd` and `--threads`, I need to build 4 versions of opencv.js. The 4 versions are **scalar version**, **threads version**, **simd version** and **threads+simd version** . 
Secondly I need to load corresponding version of opencv.js by the feedback gotten from the loader. For example, if the browser supports the simd only, the application like perf test will load the **simd version** only.

Do you think it is ok to implement?

**Comment by huningxin** [comment]
Your plan sounds good to me. @terfendail for more comments.

**Comment by huningxin** [comment]
Please implement the loader in a separate JS file so other developers can reuse it.

FYI, the `Utils` of OpenCV.js tutorials has [`loadOpenCv`](https://github.com/opencv/opencv/blob/master/doc/js_tutorials/js_assets/utils.js#L6). That could be one usage of of your loader.

**Comment by lionkunonly** [comment]
@huningxin In the implementation of loader, I meet a block at the opencv.js. In my investigation, the opencv.js building takes two stages:  `cmake` stage and `make` stage. In the `cmake` stage, the configuration for `wasm`, `threads` and `simd` is fixed. Thus, to build multiple versions of opencv.js, I have to take the `cmake` stage and `make` stage multiple times.

For example, If the user builds the opencv.js with command `--simd`, I will take the `cmake` stage with parameters for **scalar version** and `make` stage to produce the **scalar version**. Then I will take the `cmake` stage with parameters that enable the **simd** and the `make` stage again so that the **simd version** is produced. 

Do you think it is ok? Cloud you give me your suggestions?

**Comment by huningxin** [comment]
As my experience, I manage different configuration and builds in different folders such as `build_wasm`, `build_simd`, `built_mt` and `build_mt_simd`.

**Comment by lionkunonly** [comment]
> As my experience, I manage different configuration and builds in different folders such as `build_wasm`, `build_simd`, `built_mt` and `build_mt_simd`.

In this way, the `cmake` stage and `make` stage will be taken four times. Am I right? Do you think the execution of `cmake` and `make` have to be taken multiple times invetablly?

**Comment by huningxin** [comment]
For my practice, it is. I guess there are rooms to improve. However, I think this compilation optimization is not in the scope of your current task. You just need to build the four versions of opencv.js and focuses on creating a helper javascript file to load the right opencv.js depending on browser features.

**Comment by lionkunonly** [comment]
Ok, I understand. Thanks for your suggestions.

**Comment by lionkunonly** [comment]
@huningxin Hi, Ningxin. Is there a good way to check if a local file exist? I want to check if the `build_mt_simd/opencv.js` exist so that I can choos which one to load. If it does not exist, I may choose to load the `build_simd/opencv.js` or `build_mt/opencv.js`.
