### ISSUE TITLE
set LLVM upstream backend as the main backend of emscripten

### ISSUE THREAD

**Issue by Wenzhao-Xiang** [huningxin/opencv#278]
Now, the latest version of emscripten's upstream backend has support threads compiling for opencv.js, and seems the performance is better. Since only LLVM upstream backend support WASM SIMD, I suggest to replace the original fastcomp backend with the upstream backend.

I'll collect the performance data with upstream backend and show it here:
https://docs.google.com/spreadsheets/d/17TS4wBDuKUr2aN_dOPlsGDX_7Zh8_XlUU3ownv3VZHs/edit#gid=0

**Comment by Wenzhao-Xiang** [comment]
Kernel | Type | WASM(threads=8,browser,fastcomp) | WASM(threads=8,browser,upstream)
-- | -- | -- | --
-| BGR2GRAY | 0.957 | 0.734
cvtColor | YUV2BGR | 2.936 | 2.57
-| BGR2YUV | 3.091 | 2.498
resize | LINEAR_EXACT | 2.447 | 2.533

**Comment by huningxin** [comment]
+1. It serves a good base for threads+SIMD optimization. Thanks for the investigation and data.

**Comment by huningxin** [comment]
I verified the multi-threads build works with upstream backend. The cvtColor kernel with (1920x1080,COLOR_RGBA2GRAY) config shows 4.69X speedup on my 6 cores machine.

@Wenzhao-Xiang , please add this info into the document of how to build multi-threads version of OpenCV.js.

**Comment by huningxin** [comment]
We should mention this in doc: #279
