### ISSUE TITLE
Implement imread in JS

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#28]

**Comment by pancx** [comment]
Here is a method to transfer the image in web to cv.Mat.
ImageData interface of HTML canvas element represents the underlying pixel data of an area of a canvas element.
We can use the data of ImageData to construct cv.Mat, just like below.
```
var canvas = document.getElementById(canvas_id); 
var ctx = canvas.getContext('2d'); 
var imgData = ctx.getImageData(0,0,canvas.width, canvas.height); 
var src = cv.matFromArray(imgData, cv.CV_8UC4);
```

But canvas only support 8-bit UInt RGBA image.
And how to load image from a hyperlink  still need to be investigated.

**Comment by pancx** [comment]
Use --post-js command to insert js functions to opencv.js.

**Comment by huningxin** [comment]
Fixed by https://github.com/huningxin/opencv/pull/55
