### ISSUE TITLE
[SIMD] Make the code work without "__wasm_unimplemented_simd128__"

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#283]
https://github.com/huningxin/opencv/issues/257#issuecomment-521553744

**Comment by huningxin** [comment]
I asked v8 folks, they said this might be reason for cvtcolor kernel crash. So let's fix it and fallback the unimplemented to c++ impl.

**Comment by Wenzhao-Xiang** [comment]
After optimizing `v_dotprod`, the cvtcolor kernel crash issue has also been improved. Now cvtcolor kernel almost don't crash the chrome on my machine.

**Comment by huningxin** [comment]
https://github.com/huningxin/opencv/pull/287 fixes the cvtColor kernel crash issue!
