### ISSUE TITLE
[SIMD] optimize the resize kernel

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#284]
In my test with `perf_resize.html`, the mean time of scalar version is 4.35ms and the simd version is 17.21ms. We need to find the root cause and hopefully fix it.

**Comment by Wenzhao-Xiang** [comment]
That's targeted. 
I just optimized `v_dotprod` according to `Vtune`, and get a big performance improvement compared with the last version, now the mean time is 5.318 ms, almost same to scalar version 5.473ms or even better.

**Comment by huningxin** [comment]
One reason of the lower performance is the `wasm_i32x4_shl` and `wasm_i32x4_shr` are compiled to scalar version by emscripten 1.38.41. I report an issue in emscripten https://github.com/emscripten-core/emscripten/issues/9269. Let's track it there.

**Comment by Wenzhao-Xiang** [comment]
Thanks! @huningxin  
How about `wasm_v8x16_shuffle`? I found sometimes it's even slower than `wasm_i32x4_shl` and `wasm_i32x4_shr`.

**Comment by Wenzhao-Xiang** [comment]
@huningxin @terfendail Emscripten just release 1.38.42. With the latest LLVM backend, the performance of `resize` kernel get some improvement. 
* scalar: 5.319 ms
* simd: 4.410 ms

**Comment by huningxin** [comment]
That's great news. I can reproduce this number. 

As mentioned in https://github.com/emscripten-core/emscripten/issues/9269, it is fixed in latest LLVM upstream backend for latest V8. So please note the OpenCV.js built by latest LLVM upstream doesn't work with stable Chrome.

**Comment by huningxin** [comment]
And according to native SIMD to scalar speedup, there are still big room to improve. Let's follow up this later.

**Comment by huningxin** [comment]
> How about `wasm_v8x16_shuffle`?

This is an issue to get wat output of `wasm_v8x16_shuffle`, I report an issue to emscripten https://github.com/emscripten-core/emscripten/issues/9281

**Comment by huningxin** [comment]
Also open this issue in emscripten for integer widening instructions https://github.com/emscripten-core/emscripten/issues/9283

**Comment by huningxin** [comment]
@Wenzhao-Xiang , please move the info to PR.

**Comment by huningxin** [comment]
https://github.com/emscripten-core/emscripten/issues/9283 closed, we can implement it in opencv side.

**Comment by huningxin** [comment]
@lionkunonly , please report the latest perf data. Thanks!

**Comment by lionkunonly** [comment]
**Ubuntu 18.04, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, chrome dev 85.0.4183.26, and emscripten 1.39.16.**

|  | WASM Scalar (mean time) |  WASM SIMD (mean time) | SIMD speedup |
|---|---|---|---|
| resize  (CV_8UC1,640x480,960x540) | 2.2895 | 1.2878 | 1.778X |

**Comment by lionkunonly** [comment]
> [emscripten-core/emscripten#9283](https://github.com/emscripten-core/emscripten/issues/9283) closed, we can implement it in opencv side.

@huningxin  Does it mean that I need to use the widening operation in SIMD to optimize the  `v_dotprod`? 

@terfendail  Hi, vitaly. I find it is hard to find which intrinsic plays an important role in the kernel for me. Cloud you introduce me how to find out the intrinsics used in the execution of one specific kernel?

**Comment by huningxin** [comment]
> @huningxin Does it mean that I need to use the widening operation in SIMD to optimize the `v_dotprod`?

Yes. Please try that and see whether it optimizes the performance.

You can also compare it to native perf test results to know the baseline. Please refer to #259 for different build configuration (scalar or SIMD).

You can use [vtune](https://software.intel.com/content/www/us/en/develop/tools/vtune-profiler.html) as a tool to profile the perf test and see which function is hot.

**Comment by lionkunonly** [comment]
I applied the `Integer to integer widening` function in SIMD in the `v_dotprod` as the following:
```
inline v_int32x4 v_dotprod(const v_int16x8& a, const v_int16x8& b)
{
    // v128_t a0 = wasm_i32x4_shr(wasm_i32x4_shl(a.val, 16), 16);
    // v128_t a1 = wasm_i32x4_shr(a.val, 16);
    // v128_t b0 = wasm_i32x4_shr(wasm_i32x4_shl(b.val, 16), 16);
    // v128_t b1 = wasm_i32x4_shr(b.val, 16);
    v128_t a0 = wasm_i32x4_widen_high_i16x8(a.val);
    v128_t a1 = wasm_i32x4_widen_low_i16x8(a.val);
    v128_t b0 = wasm_i32x4_widen_high_i16x8(b.val);
    v128_t b1 = wasm_i32x4_widen_low_i16x8(b.val);
    v128_t c = wasm_i32x4_mul(a0, b0);
    v128_t d = wasm_i32x4_mul(a1, b1);
    return v_int32x4(wasm_i32x4_add(c, d));
}
```

Then I tested the `Resize` kernel with the input `(CV_8UC1,640x480,960x540)`, the time cost is **1.3250ms**, which is similar, and even lower than the performance that utilizing the `wasm_i32x4_shr` and `wasm_i32x4_shl`.

Then I also find that the `Integer to integer widening` function leads the errors in the `Features2D: Detectors`, `Features2D: BFMatcher`, and `Features2D: Drawing`.

I am not sure I use the `widening` function correctly. If I use it rightly, the performance brought by the `widening` function does not optimize the performance of `Resize`.

**Comment by huningxin** [comment]
I think your implementation is not correct. The tests fail as well. 

So please refer to the [v_dotprod cpp implementation](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/intrin_cpp.hpp#L965) for semantics. And please also refer to [WASM SIMD widen intrinsics](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#integer-to-integer-widening).

**Comment by lionkunonly** [comment]
@huningxin Hi, Ningxin. I modified the `v_dotprod` as following:
```
inline v_int32x4 v_dotprod(const v_int16x8& a, const v_int16x8& b)
{
    // v128_t a0 = wasm_i32x4_shr(wasm_i32x4_shl(a.val, 16), 16);
    // v128_t a1 = wasm_i32x4_shr(a.val, 16);
    // v128_t b0 = wasm_i32x4_shr(wasm_i32x4_shl(b.val, 16), 16);
    // v128_t b1 = wasm_i32x4_shr(b.val, 16);
    v128_t a0 = wasm_v8x16_shuffle(a.val, a.val, 0, 1, 4, 5, 8, 9, 12, 13, 2, 3, 6, 7, 10, 11, 14, 15);
    v128_t a1 = wasm_i32x4_widen_high_i16x8(a0);
    v128_t a2 = wasm_i32x4_widen_low_i16x8(a0);
    v128_t b0 = wasm_v8x16_shuffle(b.val, b.val, 0, 1, 4, 5, 8, 9, 12, 13, 2, 3, 6, 7, 10, 11, 14, 15);
    v128_t b1 = wasm_i32x4_widen_high_i16x8(b0);
    v128_t b2 = wasm_i32x4_widen_low_i16x8(b0);
    v128_t c = wasm_i32x4_mul(a1, b1);
    v128_t d = wasm_i32x4_mul(a2, b2);
    // v128_t e = wasm_v8x16_shuffle(c, d, 0,1,2,3,8,9,10,11,16,17,18,19,24,25,26,27);
    // v128_t f = wasm_v8x16_shuffle(c, d, 4,5,6,7,12,13,14,15,20,21,22,23,28,29,30,31);
    return v_int32x4(wasm_i32x4_add(c, d));
}
```
Now, test errors are eliminated. But I have to use the `wasm_v8x16_shuffle` and `widen intrinsics` together. I get the perf of `Resize` with this implementation. With the input `(CV_8UC1,640x480,960x540)`, the time cost is **1.4792ms**, which is lower than the performance that utilizing the `wasm_i32x4_shr` and `wasm_i32x4_shl`. I also try to do `wasm_v8x16_shuffle` after the multiplication, like the variable `e` and `f`. But the performance is worse and the time cost is **1.4968ms**.

In my opinion, utilizing `widen intrinsics` can not bring more improvement. If you find any problems or have any suggestions, please tell me.

**Comment by huningxin** [comment]
If there is no improvement, please leave with current implementation which has 1.778X speedup.

**Comment by terfendail** [comment]
I agree with Ningxin that vtune is a good option to almost automatically find out the most important place to check. The other option isn't so powerful but more available is a debugger. You could check a call stack for a breakpoint inside `v_load` to find out the deepest implementation part that use universal intrinsics. Probably that would be the place(or at least one of a few places) to look through. Of course it would be necessary to manually investigate which UI functions are used more frequent but usually it's not very hard since vectorized parts are quite short most of the time.

P.S. I don't mean to do anything with this closed issue. Just tried to answer the question above and disclosed the first step I usually do working on optimization of the code with wide universal intrinsics 😃
