### ISSUE TITLE
Implement imshow in JS

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#29]

**Comment by pancx** [comment]
As imread #28 , we can use the data of ImageData to transfer cv.Mat to canvas, just like below.
```
var imgData = new ImageData(new Uint8ClampedArray(mat.data()), mat.cols, mat.rows);
var canvas = document.getElementById(canvas_id);
var ctx = canvas.getContext("2d");
ctx.clearRect(0, 0, canvas.width, canvas.height);
canvas.width = imgData.width;
canvas.height = imgData.height;
ctx.putImageData(imgData, 0, 0);
```
But ImageData only support 8-bit UInt RGBA  image, we should manually convert mat 
to cv.CV_8UC4 type at first.
```
var dst = new cv.Mat();
cv.cvtColor(mat, dst, cv.ColorConversionCodes.COLOR_***2RGBA.value, 0); //*** is the type of mat
```
So, we may provide a helper function to detect the type of mat and convert it to ImageData.

**Comment by sajjadt** [comment]
We also like the function to have this signature ```void imshow(String winname, Mat mat)```. It might be good to have other helper functions such as ```namedWindow``` which create a canvas as well.

List of all the UI functions can be accessed here:
http://docs.opencv.org/2.4/modules/highgui/doc/user_interface.html

**Comment by huningxin** [comment]
Fixed by https://github.com/huningxin/opencv/pull/55
