### ISSUE TITLE
[SIMD] write down the optimization and hotspot analysis

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#290]
start with `v_dotprod`.

**Comment by terfendail** [comment]
I've discussed the place to put this analysis with the team. It was decided to put the analysis to GSoC related PR either as a comment or as an attached document(whatever is more convenient). There still is a discussion about a unified place to retain all results and/or reports of this GSoC. But anyway if all results of the project are stored as a PR we will be able to move them to appropriate places later.

**Comment by huningxin** [comment]
It sounds good, thanks @terfendail . @Wenzhao-Xiang , please follow that. I think we need to move those info to your PR, including

- [x] results, as https://github.com/huningxin/opencv/issues/300
- [x] analysis of the results and related emscripten/v8 issues, like https://github.com/huningxin/opencv/issues/284 #301
