### ISSUE TITLE
[SIMD] add threshold kernel into perf test (7.8X speedup)

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#291]
The SIMD optimization can be demonstrated by `threshold` kernel. The perf data of (1920x1080, 8UC1, THRESH_BINARY) on my machine:
* scalar: 1.08 ms
* simd: 0.15ms

The speedup is about 7.8X.

It would be good to add a perf test to demonstrate that.

**Comment by Wenzhao-Xiang** [comment]
Nice found! It can be reproduced on my machine with the new threshold perf test:
* scalar: 1.390 ms
* simd: 0.145 ms

**Comment by huningxin** [comment]
My data of threshold kernel with configuration (1920x1080, CV_8UC1, THRESH_BINARY) on Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz with 12 logical cores:

| build | mean time (ms) | speed up (to scalar) |
|-----|-----|----|
| scalar | 1.164 | 1 |
| threads | 0.261 | 4.45 |
| simd | 0.123 | 9.46 |
| threads + simd | 0.039 | 29.84 |
