### ISSUE TITLE
Create PR to main opencv repo

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#295]
Please create a PR based on `gosc_2019` branch to main opencv repo:
- [x] test with scalar, threads, simd, threads+simd builds
- [x] fork the branch to your own repo
- [x] squash into 1 commit with meaningful log message
- [x] rebase to opencv master branch
- [x] create PR to opencv master branch and cc @terfendail and @huningxin

**Comment by Wenzhao-Xiang** [comment]
Done. 
PR link: https://github.com/opencv/opencv/pull/15371
Close it.
