### ISSUE TITLE
[Opencv.js samples] dnn sample face recognition have a 7-8x speed up

### ISSUE THREAD

**Issue by Wenzhao-Xiang** [huningxin/opencv#299]
Face recognition: 

System: Ubuntu 16.04
Browser: Chrome, Version 78.0.3880.4 (Official Build) dev (64-bit)
Hardware: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz with ８ logical cores:

| build | FPS | speed up (to scalar) |
|-----|-----|----|
| scalar | 2-3 | 1 |
| threads | 7 | about 2-4 |
| simd | 10-11 | about 3-5 |
| threads + simd | 21-22 | about 7-10 |

I think we can take this sample as real case example.

I host this sample here(https://wenzhao-xiang.github.io/opencvjs/index.html), please help verify. @huningxin @terfendail

**Comment by huningxin** [comment]
Super! I can get 26FPS on my machine (Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz).

We may consider to add perf_dnn.js for wasm later.

**Comment by Wenzhao-Xiang** [comment]
> We may consider to add perf_dnn.js for wasm later.

@huningxin Do we put it in GSoC2019 scope?

**Comment by huningxin** [comment]
No. I mean for following work. It's excellent to have current results.

**Comment by Wenzhao-Xiang** [comment]
Ok, got it! 
Btw, could you please provide a more details about the face recognition performance data on you machine? Since I use your data of `Threshold` kernel, I'd like to unify the type of test machine. @huningxin

**Comment by huningxin** [comment]
OS: Ubuntu Linux 16.04.5
Browser: Chrome, Version 78.0.3880.4 (Official Build) dev (64-bit)
Hardware: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz with 12 logical cores

| OpenCV.js build | FPS | Speedup (to scalar) |
|----|----|----|
| scalar | 3 | 1 |
| threads | 10 | 3.33 |
| simd | 12 | 4 |
| threads + simd | 26 | 8.6 |

**Comment by Wenzhao-Xiang** [comment]
Thanks! @huningxin

**Comment by riju** [comment]
Amazing work @huningxin and @Wenzhao-Xiang !
@aleksazh and I are trying to make a ["Pro Camera" in JavaScript/PWA](https://github.com/riju/WebCamera) and  [face detection](https://riju.github.io/WebCamera/samples/faceDetection/) (scalar) was something we were trying to optimize. The threads + simd just blew our minds and yes, we are seeing similar numbers as @huningxin  just stated above.

However on mobile phones we could not take the advantage of these optimizations. We did try enabling the flags on chrome like `#enable-webassembly-threads` and `#shared-array-buffer` but we still get error like : `WebAssembly.Memory(): could not allocate memory`
![Screenshot from 2019-08-22 11-27-16](https://user-images.githubusercontent.com/975872/63499215-15d47e80-c4d0-11e9-9903-6d51124f2619.png)

Did you try the [sample](https://wenzhao-xiang.github.io/opencvjs/index.html) on a mobile phone browser ?
In our case, I don't think the app size is that great, max within 10 MB (including opencv.js around 7.5), would you know any way to increase heap size on Android for Chrome ?

**Comment by terfendail** [comment]
OS: Windows 10
Browser: Chrome, Version 76.0.3809.100 (Official Build) (64-bit)
Hardware: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz with 4 logical cores

| OpenCV.js build | FPS | Speedup (to scalar) |
|----|----|----|
| scalar | 2 | 1 |
| threads | 4 | 2 |
| simd | - | - |
| threads + simd | - | - |

**Comment by huningxin** [comment]
thanks @riju for your comments.

I didn't have a chance to test that on mobile phone browser. Did the non threads+SIMD version work on mobile chrome?

**Comment by huningxin** [comment]
@terfendail thanks for the testing, for simd built by latest emscripten (1.38.42), you need a [chrome dev edition](https://www.google.com/chrome/dev/) to verify the result.

**Comment by riju** [comment]
> thanks @riju for your comments.
> 
> I didn't have a chance to test that on mobile phone browser. Did the non threads+SIMD version work on mobile chrome?

The _**scalar**_ version worked but _**slow**_. Let us know if your team can check the simd+threads version on phones. `navigator.hardwareConcurrency` on my mobile = `8`, so ideally it _should_ work, if sufficient memory can be allocated.
