### ISSUE TITLE
[Doc] add the SIMD and threads+SIMD data of perf tests

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#300]
Please add SIMD and threads+SIMD data into the doc https://docs.google.com/spreadsheets/d/17TS4wBDuKUr2aN_dOPlsGDX_7Zh8_XlUU3ownv3VZHs/edit#gid=0.

**Comment by Wenzhao-Xiang** [comment]
Updated it.


Kernel | Type |  |   |   | Performance data(ms)  |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
|  |  | WASM(scalar) | WASM(threads=8) | WASM(SIMD128) | WASM(threads+SIMD) | Native(scalar) | Native(threads=8) | Native(SIMD128) | Native(threads+SIMD)
  | BGR2GRAY | 2.747 | 0.722 | 11.355 | 1.869 | 2.11 | 0.58 | 1.91 | 0.43
cvtColor | YUV2BGR | 12.04 | 2.636 | 27.02 | 4.757 | 7.89 | 1.97 | 3.4 | 0.86
  | BGR2YUV | 10.685 | 2.618 | 27.245 | 4.769 | 8.68 | 2.19 | 4.15 | 0.91
resize | LINEAR_EXACT | 5.425 | 2.529 | 4.309 | 1.79 | 6.45 | 2.48 | 1.03 | 0.65
threshold | THRESH_BINARY | 1.347 | 0.353 | 0.14 | 0.043 | 0.6 | 0.17 | 0.11 | 0.04

**Comment by terfendail** [comment]
IMHO This way table looks more convenient(there is no scroll, at least for a GitHub comment)
# Kernel performance(ms)

Kernel |  | cvtColor |  | resize | threshold 
--- |:---:|:---:|:---:|:---:|:---: 
**Type** | **BGR2GRAY** | **YUV2BGR** | **BGR2YUV** | **LINEAR_EXACT** | **THRESH_BINARY** 
WASM(scalar) | 2.747 | 12.04 | 10.685 | 5.425 | 1.347 
WASM(threads=8) | 0.722 | 2.636 | 2.618 | 2.529 | 0.353 
WASM(SIMD128) | 11.355 | 27.02 | 27.245 | 4.309 | 0.14 
WASM(threads+SIMD) | 1.869 | 4.757 | 4.769 | 1.79 | 0.043 
Native(scalar) | 2.11 | 7.89 | 8.68 | 6.45 | 0.6 
Native(threads=8) | 0.58 | 1.97 | 2.19 | 2.48 | 0.17 
Native(SIMD128) | 1.91 | 3.4 | 4.15 | 1.03 | 0.11 
Native(threads+SIMD) | 0.43 | 0.86 | 0.91 | 0.65 | 0.04

**Comment by huningxin** [comment]
@Wenzhao-Xiang , please move the data to PR, then close it.

**Comment by Wenzhao-Xiang** [comment]
Done, closed it.
