### ISSUE TITLE
[SIMD] optimize the cvtColor kernel

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#301]
According to https://github.com/huningxin/opencv/issues/300#issuecomment-524790373, the SIMD `cvtColor` kernel is times slower than scalar version. 

According to my investigation, the root cause is the inefficient `pshufb` with memory operands are generated by V8 for current implementation. 

One solution is to refer to [sse implementation](https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/hal/intrin_sse.hpp#L1871) that uses `punpcklbw` and `punpckhqdq`. I tried but it still fails due to an [emscripten issue](https://github.com/emscripten-core/emscripten/issues/9340) that leads V8 fails to generate those instructions. Let's see the response from emscripten community.

**Comment by huningxin** [comment]
@Wenzhao-Xiang , please move this info to PR for record.

**Comment by huningxin** [comment]
Link to https://github.com/WebAssembly/simd/issues/196

**Comment by huningxin** [comment]
@lionkunonly , please report the latest perf data you have. Thanks!

**Comment by lionkunonly** [comment]
**Ubuntu 18.04, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, chrome dev 85.0.4183.26, and emscripten 1.39.16.**

|  | WASM Scalar (mean time) |  WASM SIMD (mean time) | SIMD speedup |
|---|---|---|---|
| CvtColor  (1920x1080,COLOR_RGBA2GRAY) | 2.4161 | 2.8215 | 0.86X |

**Comment by lionkunonly** [comment]
@huningxin Hi, Ningxin. I am not sure how to optimize the CvtColor. Do you have more suggestions in detail?

**Comment by huningxin** [comment]
As mentioned in https://github.com/huningxin/opencv/issues/301#issuecomment-596299378, this issue depends on https://github.com/WebAssembly/simd/issues/196 and https://github.com/emscripten-core/emscripten/issues/9340. 

Compared to [the last year's performance](https://github.com/opencv/opencv/pull/15371) (0.24X), your latest data (0.86X) is 3.5X faster.

It seems WebAssembly community is still working on that. Let's monitor and test if there is new progress.
