### ISSUE TITLE
[SIMD] Check if `wasm_f32x4_sqrt` is still unimplemented with the latest emscripten LLVM backend

### ISSUE THREAD

**Issue by Wenzhao-Xiang** [huningxin/opencv#302]

**Comment by Wenzhao-Xiang** [comment]
@akineeic @huningxin Help checked it. 
It's still unimplemented with the latest emscripten LLVM backend.
Opened an [emscripten issue here](https://github.com/emscripten-core/emscripten/issues/9399).

**Comment by huningxin** [comment]
should revisit it.

**Comment by lionkunonly** [comment]
`wasm_f32x4_sqrt` is implemented now.  And it is applied in the WASM SIMD version

**Comment by huningxin** [comment]
> `wasm_f32x4_sqrt` is implemented now. And it is applied in the WASM SIMD version

Good. Then please fix them in intrin_wasm.hpp, e.g.

https://github.com/huningxin/opencv/blob/master/modules/core/include/opencv2/core/hal/intrin_wasm.hpp#L2611

**Comment by lionkunonly** [comment]
@huningxin  It is fixed in the branch `gsoc_2020_simd`. Do I need to fix it in the master?

**Comment by huningxin** [comment]
No, it would be fine.
