### ISSUE TITLE
[Perf] add more kernels into perf test

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#304]
Per https://github.com/huningxin/opencv/issues/260#issuecomment-500885482

- [x] cvtColor(especially BGR2GRAY, YUV2BGR, BGR2YUV)
- [x] resize(especially LINEAR_BITEXACT/LINEAR)
- [x] Sobel
- [x] filter2D
- [x] Scharr
- [x] gaussianBlur
- [x] blur
- [x] medianBlur
- [x] erode
- [x] dilate
- [ ] morphologyEx (skipped)
- [x] remap
- [x] warpAffine
- [x] warpPerspective
- [x] pyrDown
- [ ] buildPyramyd

**Comment by huningxin** [comment]
Hi @lionkunonly , with #357 done, I think you can go ahead to add more kernels including filter2D into the js perf test. 

With that, you can collect the performance and give us a whole picture and disclose any perf issues within current implementation. Lacking of good coverage of perf tests is one major missing part of last year's GSoC. Please help close that.

@terfendail , what do you think?

**Comment by terfendail** [comment]
I definitely agree that small perf test coverage is a major issue we have to deal with. Anyway we can't go further with performance improvement until we have the tool to measure the progress.

**Comment by lionkunonly** [comment]
There are two more frequently used kernels:
- [ ] addWeighted
- [ ] add

I also I want to add perf tests for them.

**Comment by terfendail** [comment]
While these kernels are used really often they are quite simple. So they use just a few universal intrinsics which are also quite simple.
It could be interesting to check the performance against the c++ baseline, but WASM version probably couldn't be optimized further. As far as I could remember addition and multiplication both are mapped to single WASM intrinsic so there is no place for improvement and the only intrinsic to improve is `v_fma` for addWeighted

**Comment by lionkunonly** [comment]
Record performance data in this issue. And compare the performance data with native opencv with the scalar version and the SIMD version.

**Comment by lionkunonly** [comment]
In the process of developing perf test for `filter2D`. I find there is a binding error for opencv.js. This error happens on the API `cv::randu`. 

In the native opencv, the parameters of `randu` is `void cv::randu(InputOutputArray dst, InputArray low, InputArray high)`. But in the opencv.js, it is `void randu_wrapper(cv::Mat& arg1, const cv::Mat& arg2, const cv::Mat& arg3)`, and it just use the `Mat` type `arg2` and `arg3` as the input `low` and `high` in the native implementation, which causes an error.

**Comment by lionkunonly** [comment]
Performance test:
| Kernel  | Scalar |  Threads(thread=12) |  SIMD  | Threads(threads=12) + SIMD |
| ------ |-------| ----------| -----| ------|
| filter2d (1920x1080,3,BORDER_CONSTANT) |  78.64 | 79.19 | 18.13 |  18.08 |
| Sobel (640x480, CV_16SC1, (0,1), BORDER_REPLICATE) ksize=5 | 1.57 | 1.50 | 0.88 | 0.84 |

**Environment: Ubuntu 18.04, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, chrome dev 85.0.4183.26, and emscripten 1.39.16.** 

PS. In the perf test, I find a strange phenomenon. If I open the Dev tool in chrome. The time cost will be more. I do not know which cause it.

**Comment by terfendail** [comment]
I've check the native implementation - there is no multi-thread support internally for Sobel. So it's expected result to have same performance with and without threads. There is also no multi-thread support in Scharr and Filter2d and blur. For GaussianBlur multi-thread support implemented for 8U bitexact only.

**Comment by lionkunonly** [comment]
@terfendail I find that the kernel `buildPyramyd` is not supported in `opencv.js`. I think this kernel should be skipped. Could you give your suggestions?

**Comment by terfendail** [comment]
I think it's OK to skip `buildPyramid` in that case

**Comment by lionkunonly** [comment]
@huningxin @terfendail  I want to check the configuration for native perf tests. For the `Native(scalar)`, it only uses the CPU optimization with `SSE2`. For the `Native(simd)`, it uses all CPU optimization. Is it right? Or the `Native(scalar)` takes no optimization and the `Native(simd)` only uses `SSE2`.

I think the first option is more reasonable.

**Comment by lionkunonly** [comment]
[Perf data](https://docs.google.com/spreadsheets/d/1lVPdlLLSET1WT7yJZquSLcBgDcVtaExAbFk6Boxwjoo/edit?usp=sharing) is here. You can check out it to know the gap between the performance of opencv.js and the native. The result in Google Drive is supported comment, now.
