### ISSUE TITLE
[SIMD] implement the type 64 intrinsics

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#306]
They are `f64`, `i64`, `u64`. Current they use fallback implementation.

**Comment by huningxin** [comment]
@lionkunonly asked whether there are any performance tests of 64 bit intrinsics in native opencv. @terfendail , could you please help check? Thanks!

**Comment by terfendail** [comment]
I think the most affected function should be `countNonZero()` for `CV_64F`. `minMaxIdx()` and `Mat::dot()` could also be affected. `split()` and `merge()` functions are affected too, but they use just `vx_load/v_store` subset so could be less representative.

**Comment by lionkunonly** [comment]
@huningxin  Hi, Ningxin. I find there are some statements `#ifdef __wasm_unimplemented_simd128__` in the file `intrin_wasm.hpp`. What should I do for them? Just delete them?

**Comment by huningxin** [comment]
You should check against "wasm_simd128.h" of the your emscripten, e.g. 1.39.16. If an intrinsic is not guarded by `__wasm_unimplemented_simd128__` anymore, you should remove the guard and use that intrinsic in "intrin_wasm.hpp" accordingly. The current usage of this guard in "intrin_wasm.hpp" was done in last GSoC, you need to update it.

**Comment by huningxin** [comment]
> I think the most affected function should be `countNonZero()` for `CV_64F`. `minMaxIdx()` and `Mat::dot()` could also be affected.

Thanks @terfendail , I think they are good ones for 64 bit intrinsics perf test. Created https://github.com/huningxin/opencv/issues/340 to track it.

**Comment by huningxin** [comment]
As #342 merged, close this one.
