### ISSUE TITLE
[DNN] Investigate object detection python example

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#314]
https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py

**Comment by akineeic** [comment]
The whole process  is similar to image classification, except the post processing.  The processing information mainly includes input size, mean, std, RGB or BGR, output type and the labels txt file . The models predict correctly yet are as follows: 

- caffe

Model | input size | mean | std | rgb | output type | labels txt
:------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: 
MobileNet SSD | 300, 300 | 127.5, 127.5, 127.5 | 0.007843 | ture | SSD | pascal
VGG SSD | 300, 300 | 104, 117, 123 | 1 | ture | SSD | pascal

- darknet

Model | input size | mean | std | rgb | output type | labels txt
:------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: | :-------------: 
Yolo V2 | 416, 416 | 0, 0, 0 | 0.00392 | ture | YOLO | yolo
Yolo V2 tiny | 416, 416 | 0, 0, 0 | 0.00392 | ture | YOLO | yolo
