### ISSUE TITLE
[DNN] Investigate segmentation python example

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#315]
https://github.com/opencv/opencv/blob/master/samples/dnn/segmentation.py

**Comment by akineeic** [comment]
I have tested the models for semantic segmentation in the [wiki](https://github.com/opencv/opencv/wiki/Deep-Learning-in-OpenCV). The [ResNet101_DUC_HDC](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/duc) can't be read correctly and the output image of [Enet](https://github.com/e-lab/ENet-training) doesn't look good visually. I have report these issues ([ResNet101_DUC_HDC](https://github.com/opencv/opencv/issues/17931), [Enet](https://github.com/opencv/opencv_extra/pull/648)) to upstream and get some guidelines.
