### ISSUE TITLE
[DNN] add colorization js example

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#320]
python version: https://github.com/opencv/opencv/blob/master/samples/dnn/colorization.py

**Comment by akineeic** [comment]
Since the example in python need to [load model weight](https://github.com/opencv/opencv/blob/master/samples/dnn/colorization.py#L28-L33) from a `npy` file. But the related API isn't enabled in opencv.js. So I don’t consider deploying this example for now.
