### ISSUE TITLE
[GPU] investigate the vkcom module

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#323]
https://github.com/opencv/opencv/tree/master/modules/dnn/src/vkcom

**Comment by NALLEIN** [comment]
Vulkan and DAWN/WebGPU API mapping list:

Vulkan | Dawn
-- | --
 **Stage**  |  **Create Instance&Device**
vkCreateInstance | wgpuInstanceCreateSurface/   wgpuInstanceRequestAdapter
vkEnumeratePhysicalDevices | wgpuAdapterGetProperties
vkCreateDevice | wgpuAdapterRequestDevice
**Stage**  |  **BufferManager Buffer Create/Read/Write/Destroy**
vkCreateBuffer/   vkGetBufferMemoryRequirements | wgpuDeviceCreateBuffer\   wgpuDeviceCreateBufferMapped
vkAllocateMemory |  
vkMapMemory/       vkUnmapMemory | wgpuBufferMapWriteAsync\ wgpuBufferMapReadAsync   wgpuBufferUnmap
vkBindBufferMemory |  
vkGetDeviceQueue | wgpuDeviceGetDefaultQueue
vkFreeMemory\   vkDestroyBuffer | wgpuBufferDestroy
 **Stage** |  **CommandBuffer & CommandQueue**
vkCreateCommandPool | wgpuDeviceCreateCommandEncoder
vkAllocateCommandBuffers |  
vkBeginCommandBuffer\   vkEndCommandBuffer | wgpuCommandEncoderBeginComputePass\   wgpuCommandEncoderFinish
vkCreateFence | wgpuQueueCreateFence
vkQueueSubmit | wgpuQueueSubmit
vkCmdPushConstants\   vkCmdBindPipeline\   vkCmdBindDescriptorSets\   vkCmdDispatch | wgpuComputePassEncoderSetPipeline\   wgpuComputePassEncoderSetBindGroup\   wgpuComputePassEncoderDispatch
vkWaitForFences\   vkDestroyFence | wgpuFenceGetCompletedValue\   wgpuFenceOnCompletion
**Stage**  |  **Compute PipeLine & ShaderModule**
vkCreateDescriptorSetLayout | wgpuDeviceCreateBindGroupLayout
vkCreateDescriptorPool\   vkAllocateDescriptorSets | wgpuDeviceCreateBindGroup
vkCreateShaderModule | wgpuDeviceCreateShaderModule
vkCreatePipelineLayout\   vkCreateComputePipelines | wgpuDeviceCreatePipelineLayout\   wgpuDeviceCreateComputePipeline

Dawn can be seen as a wrapper for Vulkan / D3D12 / Metal in the Web
