### ISSUE TITLE
Add JS functions into manual

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#33]
refer to : http://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html

```void absdiff(InputArray src1, InputArray src2, OutputArray dst)```

**Comment by huningxin** [comment]
@sajjadt , I cannot find such style in 3.x doc: http://docs.opencv.org/3.2.0/. Could you please point it out? Thanks!

**Comment by sajjadt** [comment]
@huningxin Turns out they switched to Doxygen from Sphinx in OpenCV 3 and it is not possible to document Java/Python using Doxygen at the moment.

**Comment by huningxin** [comment]
As we only support OpenCV 3, close this issue.

**Comment by huningxin** [comment]
And we added API doc into the tutorial page, e.g. https://huningxin.github.io/opencv_docs/tutorial_js_colorspaces.html
