### ISSUE TITLE
[SIMD] add perf tests for 64bit intrinsics

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#340]
As @terfendail mentioned in https://github.com/huningxin/opencv/issues/306#issuecomment-640563017, there are

- [x]  `countNonZero()` for CV_64F. 
- [ ] `minMaxIdx()`
- [x] `Mat::dot()` 
- [x] `split()`
- [x] `merge()`

**Comment by lionkunonly** [comment]
The API `minMaxIdx` is not appeared in the `bindings.cpp`. I only find the API `minMaxLoc`.

**Comment by huningxin** [comment]
@lionkunonly , if a function is not in https://github.com/huningxin/opencv/blob/master/modules/js/src/core_bindings.cpp, you can check in this file: https://github.com/huningxin/opencv/blob/master/platforms/js/opencv_js.config.py that contains the generated ones.

If there is not `minMaxIdx` in both files, I would suggest to skip it first.

**Comment by huningxin** [comment]
@lionkunonly , please send a PR that adds these kernels into perf tests. We can measure and optimization the performance as the next step. Thanks!

**Comment by lionkunonly** [comment]
The perf tests are integrated in the file ` modules/js/test/test_64bit.js`. It is used in the `modules/js/test/tests.html`. The performance about time cost is printed in the console. Please check it.

**Comment by huningxin** [comment]
@lionkunonly , please report the initial perf data of 64bit intrinsics here. Thanks.

**Comment by huningxin** [comment]
> @lionkunonly , please report the initial perf data of 64bit intrinsics here. Thanks.

@lionkunonly , please update that and we can close this issue. Thanks!

**Comment by lionkunonly** [comment]
@huningxin. The perf of 64bit intrinsics is here.

**Ubuntu 16.04, Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, chrome dev 85.0.4158.4, and emscripten 1.39.16.**

|  Kernel  | Before 64bit implementation (ms) |  After 64bit implementation (ms) | Speedup |
|---|---|---|---|
| countNonZero()  | 0.6229 | 0.6240  | 0.998x |
| Mat::dot() | 1.4242 | 1.3906 | 1.024x |
| split()  | 3.9420 | 3.8305 |  1.029x |
| merge() | 3.8604 | 3.8375 | 1.006x  |

**Ubuntu 16.04, Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, chrome dev 85.0.4183.26, and emscripten 1.39.16.**

|  Kernel  | Before 64bit implementation (ms) |  After 64bit implementation (ms) | Speedup |
|---|---|---|---|
| countNonZero()  | 1.0198 | 1.0230  | 0.997x |
| Mat::dot() | 1.4207 | 1.4031 | 1.025x |
| split()  | 4.3018 | 4.3070 |  0.999x |
| merge() | 4.6332 | 4.6066 | 1.006x  |

As we can see the performance of kernels after 64-bit implementation is similar to the performance before implementation.  Meanwhile, in the latest chrome dev version 85.0.4183.26, the time cost of these kernels is more.

**Comment by huningxin** [comment]
Thanks for the data @lionkunonly , could you please collect the data on the 8th gen CPU?

**Comment by lionkunonly** [comment]
@huningxin. The perf of 64bit intrinsics is here.

**Ubuntu 18.04, Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, chrome dev 85.0.4183.26, and emscripten 1.39.16.**

|  Kernel  | Before 64bit implementation (ms) |  After 64bit implementation (ms) | Speedup |
|---|---|---|---|
| countNonZero()  | 0.5386 | 0.5221  | 1.032x |
| Mat::dot() | 0.8079 | 0.7960 | 1.015x |
| split()  | 2.1213 | 2.0483 |  1.036x |
| merge() | 2.2383 | 2.2264 | 1.005x  |

The performance of kernels after 64-bit implementation is similar to the performance before implementation on the 8th gen CPU.

**Comment by huningxin** [comment]
Thanks. Let's close it.
