### ISSUE TITLE
[SIMD] add required emscripten version into opencv.js build instructions

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#347]

**Comment by lionkunonly** [comment]
Should I investigate which emscripten version can support this new 64-bit feature? For example, I use version 1.39.16 now, and I need to verify the 1.39.15, 1.39.14, 1.39.13, and so on.

**Comment by huningxin** [comment]
Please document the emscripten version you are using, e.g. 1.39.16.

**Comment by lionkunonly** [comment]
@huningxin , @terfendail . Is there any existing docs that record the emscripten version for build instructions? I don't find such files. Should I create a new doc?

**Comment by huningxin** [comment]
https://github.com/huningxin/opencv/blob/master/doc/js_tutorials/js_setup/js_setup/js_setup.markdown

**Comment by lionkunonly** [comment]
The PR for adding the required emscripten version is merged. I think this issue should be closed.
