### ISSUE TITLE
[GPU] add dnn test layer for softmax

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#352]

**Comment by huningxin** [comment]
a softmax layer example in onnx importer test: https://github.com/opencv/opencv/blob/master/modules/dnn/test/test_onnx_importer.cpp#L69

**Comment by wzw-intel** [comment]
sample of unit test for a specific layer:
https://github.com/opencv/opencv/blob/master/modules/dnn/test/test_layers.cpp#L1589

**Comment by NALLEIN** [comment]
Fix in [this PR](https://github.com/huningxin/opencv/pull/338).
