### ISSUE TITLE
transfer image data to mat.data

### ISSUE THREAD

**Issue by pancx** [huningxin/opencv#36]

**Comment by pancx** [comment]
Using canvas ImageData to transfer image data to mat.data is limited.
1. only 8-bit rgba image supported.
2. the data should be continuous storage
Other ways to implement imread still need to be investigated , but it is not urgent.

**Comment by huningxin** [comment]
@pancx , I think we can include this info into the imread doc, then close this issue. That do you think?

**Comment by pancx** [comment]
@huningxin  Fine.

**Comment by pancx** [comment]
This has been mentioned in tutorial of  `Getting Started with Images`(#159 ), and could be closed.
