### ISSUE TITLE
[dnn] add model info json to all tutorials

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#366]
- [x] semantic segmentation 
- [x] object detect
- [x] style transfer
- [x] pose estimation

**Comment by huningxin** [comment]
any updates @akineeic ?

**Comment by akineeic** [comment]
> any updates @akineeic ?

Sorry for the late reply. I have updated in the upstream [PR](https://github.com/opencv/opencv/pull/18064). Or should I create a PR in your repo at the same time?

**Comment by huningxin** [comment]
> Or should I create a PR in your repo at the same time?

No. Please just update the progress in the upstream PR. Thanks!
