### ISSUE TITLE
cv::Mat clone() gives wrong value

### ISSUE THREAD

**Issue by pancx** [huningxin/opencv#37]
While using clone(), it gives wrong value sometimes. For example, in featrues_2d.html line 179, change img to img.clone(), there will be some wrong value in the row 1 of the output image, just like the attach file.

![new bitmap image](https://user-images.githubusercontent.com/16699894/27567311-94818120-5b1d-11e7-8eeb-68c67bb04569.jpg)

**Comment by sajjadt** [comment]
@pancx  Hmm, good catch. What algorithm is used to generate the right picture? Seems like a filter or color conversion.

**Comment by pancx** [comment]
@sajjadt  it is mser algorithm. But I find it has no connection with algorithm. When transfer the data of 4 channels image, it will occur. 
For example, in img_proc.html makeBGRA()
'''
cv.cvtColor(src, res, cv.ColorConversionCodes.COLOR_RGBA2BGRA.value, 0);
'''
The wrong value will appear.
![new bitmap image](https://user-images.githubusercontent.com/16699894/27669065-6b5dc74a-5cb7-11e7-885b-f67a34a2cae4.jpg)

**Comment by sajjadt** [comment]
@pancx It worth checking that we are not getting the same erroneous result in native build of OpenCV. Maybe there is a bug there.

**Comment by huningxin** [comment]
@pancx , any updates?

**Comment by huningxin** [comment]
Native sample doesn't have this issue.
```
#include "opencv2/imgcodecs.hpp"
#include "opencv2/highgui.hpp"
#include <iostream>
using namespace cv;
using namespace std;
int main( void )
{
   Mat src, dst;
   src = imread( "/home/nhu/Pictures/lena.png" );
   dst = src.clone();
   imshow( "Lena", dst );
   waitKey(0);
   return 0;
}
```

However, equivalent JS `clone` will have corrupted images.

**Comment by huningxin** [comment]
From my understanding, the current `matFromArray` implementation might have some memory issue:
```
emscripten::val  matFromArray(const emscripten::val& object, int type) {
    int w=  object["width"].as<unsigned>();
    int h=  object["height"].as<unsigned>();
    std::string str = object["data"]["buffer"].as<std::string>();
    
    return emscripten::val(cv::Mat(h, w, type, (void*)str.data(), 0));
}
```
As http://docs.opencv.org/3.2.0/d3/d63/classcv_1_1Mat.html#a51615ebf17a64c968df0bf49b4de6a3a, the `Mat` will not own or copy the data. So `str.data()` will be released after this function returns which leads Mat points to invalid memory.

**Comment by huningxin** [comment]
#74 attempts to fix it. However, it introduces another memory copy. So `matFromArray` will have two memory copies:
1. `std::string str = object["data"]["buffer"].as<std::string>();` copy memory from image data buffer to emscripten heap as string buffer.
2. `memcpy(mat.data, str.data(), mat.total()*mat.elemSize());` copy memory from string buffer to Mat managed buffer.

We can reduce to one memory copy by setting Mat buffer directly, as:
```js
var mat = new cv.Mat(imgData.width, imgData.height, cv.CV_8UC4);
mat.data().set(imgData.data);
```
