### ISSUE TITLE
[DNN] create project final report and video

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#371]

**Comment by akineeic** [comment]
@huningxin  You can check my [report](https://gist.github.com/akineeic/61c1f548350fa8dc99f174ed1f06cce8)  in gist. Could you please take a look, any suggestion is welcomed sincerely.

**Comment by huningxin** [comment]
Are you able to provide the inference time for threads and simd builds, including threads, simd and threads+simd? Thanks!

**Comment by akineeic** [comment]
> Are you able to provide the inference time for threads and simd builds, including threads, simd and threads+simd? Thanks!

Fine I'll do it later.

**Comment by akineeic** [comment]
My video report on youtube can be found [here](https://youtu.be/Stbb4hZCkhU).

**Comment by huningxin** [comment]
Looks good. Thanks much @akineeic !
