### ISSUE TITLE
[SIMD] create the final project report and video

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#372]

**Comment by lionkunonly** [comment]
@huningxin @terfendail  Hi, Ningxin and Vitaly. My final report has been completed without the demos. You can check it here [Project Report](https://gist.github.com/lionkunonly/bbb50a839faf7acd1543f142d45254f6). You can leave your comments on the copy file I stored in the Google driver here [Report in Google drive](https://docs.google.com/document/d/1cZ9vbZca7uhwTpzo1mNYfbBkfWAPF-iFo6rbNQph4uo/edit?usp=sharing).  Any suggestion is accepted sincerely.
