### ISSUE TITLE
[GPU] create the final project report and video

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#373]

**Comment by huningxin** [comment]
example project report: https://gist.github.com/Wenzhao-Xiang/8636e239c20e0eda839833f9d363828e
example video: https://www.youtube.com/watch?v=ertdEzqE6bI&feature=youtu.be

**Comment by NALLEIN** [comment]
[GSoC report](https://gist.github.com/NALLEIN/d7e0357574a958b7a8edb442e3488271)
[Demo](https://nallein.github.io/opencvjs/index.html) (layer test, requires the latest chrome dev/canary on macOS/windows and enable chrome://flags Unsafe WebGPU)
[Video](https://youtu.be/ZjOEMzp-0ys)
