### ISSUE TITLE
[WEBNN] Test webnn cmake by reading README.md

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#376]
@MarkGHX 

Please share with me the repo and README.md. I'd like to test on my side.

**Comment by MarkGHX** [comment]
@huningxin 

Hi Ningxin, the link of README.md is https://github.com/MarkGHX/opencv/tree/master/modules/dnn/src/webnn. Please check it. Thanks!

**Comment by huningxin** [comment]
Hi @MarkGHX , there is a typo "DNN_BACKEND_WEBGPU". Do you mean DNN_BACKEND_WEBNN?

**Comment by huningxin** [comment]
Please use the public repo link of webnn-native: https://github.com/webmachinelearning/webnn-native

**Comment by huningxin** [comment]
I didn't set `WEBNN_NATIVE_DIR`, but there is no error reporting when I executed `cmake -D CMAKE_BUILD_TYPE=Release -DWITH_WEBNN=ON -D CMAKE_INSTALL_PREFIX=/usr/local ..`

**Comment by huningxin** [comment]
@MarkGHX , please take a look at above three issues. Thanks!

**Comment by MarkGHX** [comment]
@huningxin Hi NIngxin, I have fixed the typo and the link issue in the README.md.

**Comment by MarkGHX** [comment]
I also changed the compile command in the README.md to fit the official doc. Using the new commanad, if I did not export WEBNN_NATIVE_DIR, the code could not be compiled successfully. And after I export the WEBNN_NATIVE_DIR, the code could be compiled.

**Comment by huningxin** [comment]
@MarkGHX Thanks for the update. I'd like to keep reviewing and commenting your code. Could you please create a PR to this branch https://github.com/huningxin/opencv/tree/gsoc_2021_webnn?

**Comment by MarkGHX** [comment]
@huningxin Hi Ningxin, I've created a PR to gsoc_2021_webnn branch. Please check it. Thanks!

**Comment by huningxin** [comment]
Great, I've left some comments there. Please take a look. Thanks.

**Comment by huningxin** [comment]
closed by #382
