### ISSUE TITLE
Implement inline interactive tutorials

### ISSUE THREAD

**Issue by pancx** [huningxin/opencv#38]
We need interactive tutorials, which embed html elements and let people try the code in the tutorial pages .
But now, markdown doesn't support html5, including many html elements we need.

As a temporary solution, I will make independent interactive  pages, and give the link in tutorial pages.

**Comment by pancx** [comment]
Gang found that \htmlonly command could insert html in markdown. I will try it.

**Comment by huningxin** [comment]
It's great! Thanks @pancx @remember08 !

Please also paste a link to the page of `\htmlonly` as reference.

**Comment by pancx** [comment]
\htmlonly and \endhtmlonly http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdhtmlonly

**Comment by huningxin** [comment]
Let's target it in M3.

**Comment by huningxin** [comment]
Fixed by https://github.com/huningxin/opencv/pull/55.

See https://huningxin.github.io/opencv_docs/tutorial_js_table_of_contents_gui.html
