### ISSUE TITLE
Integrate opencvjs tests into js module

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#4]
refer to https://github.com/opencv/opencv/tree/master/modules/python/test, using node.js

**Comment by pancx** [comment]
First, support to run tests on browser
a. copy the test files from ucisysarch/opencvjs/test.
b. rename cv.js to opencv.js
c. create preloaded file before using.
Second, support to run tests on Node.js
a. add package.json to add dependence of qunit.
b. add tests.js to require qunit and auto run tests.
c. in tests, require opencv.js as cv when the envrionment is Node.js
Usage:
npm install
node tests.js

**Comment by huningxin** [comment]
Good 1st step to have initial tests imported and integrated into the opencv. We may need to add more tests later. Let's close.
