### ISSUE TITLE
Introduce CV_WRAP_JS and annotate the functions exposing to JS

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#40]
Paste @sajjadt 's original idea here. Please feel free to update.

"
I've also attached the list of important OpenCV functions that we want in our binding. This helps making the generated binary much smaller. We also want to cover only these functions in tutorials. To generate bindings for these functions, I suggest to define a new Macro e.g. CV_WRAP_JS and annotate the functions with it. Then binding generator can recognize these functions.
"

**Comment by sajjadt** [comment]
Can we handle #33 with current function whit list approach?

**Comment by huningxin** [comment]
Good point. We need to investigate it and report back.

**Comment by huningxin** [comment]
Close this one, as we go with white list approach.
