### ISSUE TITLE
Implement tutorial of video input & output

### ISSUE THREAD

**Issue by pancx** [huningxin/opencv#58]
It is the first step of #21  .
And we will investigate WebRTC to implement it.

**Comment by pancx** [comment]
Taking still photos with WebRTC, 
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos

**Comment by sajjadt** [comment]
This can be used for the interoperability layer: https://github.com/webrtc/adapter
Few sample tests from Mozilla: https://mozilla.github.io/webrtc-landing/
