### ISSUE TITLE
[Mat] constructor doesn't support Scalar parameter

### ISSUE THREAD

**Issue by ganwenyao** [huningxin/opencv#60]
In C++, there is a Mat constructor : 

```C++
cv::Mat::Mat(int rows, int cols, int type, const Scalar &s )	
```
but there is not a similar cv.Mat constructor in opencv.js.

**Comment by sajjadt** [comment]
This is due to a limitation on function overloading. We can only have one function with same number of parameters. Currently the following function is using that slot.  

```c++
Mat(Size size, int type, intptr_t data, size_t step)
```

This decision is made for the sake of performance. By extending JS side (embind.js for instance)  it is possible to select functions based on the signature and not the parameters count.

**Comment by huningxin** [comment]
@ganwenyao , would you please show some JS code that with and without this API supported? Thanks!

**Comment by ganwenyao** [comment]
We can use the following JS function to replace the Mat constructor In C++:
```javascript
function matFromScalar (cols, rows, type, scalar) {
	var scalarMat = new cv.Mat(cols, rows, type);
	for (var i=0;  i < cols*rows*scalarMat.channels(); ++i) {
		scalarMat.data()[i] = scalar[i%scalarMat.channels()];
	}
	return scalarMat;
}
```

**Comment by huningxin** [comment]
By using `int row, int cols` instead of `Size` for constructor with `void* data`, we can accommodate 4 constructors, as
```
cv::Mat(cv::Size sz, int type ); // 2 parameters
cv::Mat(int rows, int cols, int type ); // 3 parameters
cv::Mat(int rows, int cols, int type, const Scalar& s); // 4 parameters
cv::Mat(int rows, int cols, int type, void* data, size_t step); // 5 parameters
```
constructor with `const Scalar& s` is used in img processing examples. It is better to expose it.

@sajjadt , what do you think?

**Comment by sajjadt** [comment]
I like the way last three constructors are consistent in using rows and cols.
