### ISSUE TITLE
cv.imshow() doesn't support Mat with types except CV_8UC4

### ISSUE THREAD

**Issue by ganwenyao** [huningxin/opencv#61]
Type transformation should be included in  cv.imshow().

**Comment by huningxin** [comment]
@ganwenyao , would you please specify the details? like what the API looks like and what parameters should be supported.

**Comment by pancx** [comment]
As far as I know, the native imshow only recognize the below numerical ranges of different cv.Mat types. 
```
- CV_8U     [0, 255]
- CV_8S     [-128, 127]
- CV_16U    [0, 255 * 256]
- CV_16S    [-128 * 256, 127 * 256]
- CV_32S    [0, 255 * 256]
- CV_32F    [0.0, 1.0]
- CV_64F    [0.0, 1.0]
```
Then native imshow will map the above numerical ranges to [0, 255].
In addition, native imshow only could display mats with 1, 3, 4 channels.

I will implement this in cv.imshow, by using cv.Mat.convertTo and cv.cvtColor .
