### ISSUE TITLE
Create utils.js for common functions used in different tutorials

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#64]
Like
```js
function loadImageToCanvas(url, cavansId) {
  let canvas = document.getElementById(cavansId);
  let ctx = canvas.getContext('2d');
  let img = new Image();
  img.crossOrigin = 'anonymous';
  img.onload = function() {
    canvas.width = img.width;
    canvas.height = img.height;
    ctx.drawImage(img, 0, 0, img.width, img.height);
  }
  img.src = url;
}
```

Put it into utils.js and different tutorial pages can share it.

**Comment by sajjadt** [comment]
Can we just implement this feature using one ```imread``` and one ```imshow``` calls?  Same functions are used in both C++ and Ptyhon APIs and we want it here as well.

These two functions, should be part of another module, for instance highgui.js which is a web version for Highgui library..

 
```
 C++: void imshow(const string& winname, InputArray mat)
```
```
JS: void imshow(canvasname, mat)
```

then we can add  more functions such as, ```namedWindow``` [link](http://docs.opencv.org/2.4/modules/highgui/doc/user_interface.html#namedwindow) that creates a canvas.

**Comment by pancx** [comment]
Good idea! I will create utils.js in js_assets folder. It will be copied to tutorials' target folder while making doxygen.
And use it by adding `<script src="utils.js"></script>` in tutorials.
