### ISSUE TITLE
Meta: Implementing HighGUI and Media IO functions

### ISSUE THREAD

**Issue by sajjadt** [huningxin/opencv#68]
Here's the list of all the functions provided by HighGui library. we need to implement a subset of them in JS. I've borrowed the list from [here](http://docs.opencv.org/2.4/modules/highgui/doc/highgui.html).

#### User Interface
        createTrackbar
        getTrackbarPos
        imshow
        namedWindow
        destroyWindow
        destroyAllWindows
        MoveWindow
        ResizeWindow
        SetMouseCallback
        setTrackbarPos
        waitKey
        setOpenGlDrawCallback
        setOpenGlContext
        updateWindow
 #### Reading and Writing Images and Video
        imdecode
        imencode
        imread
        imwrite
        VideoCapture
        VideoCapture::VideoCapture
        VideoCapture::open
        VideoCapture::isOpened
        VideoCapture::release
        VideoCapture::grab
        VideoCapture::retrieve
        VideoCapture::read
        VideoCapture::get
        VideoCapture::set
        VideoWriter
        VideoWriter::VideoWriter
        ReleaseVideoWriter
        VideoWriter::open
        VideoWriter::isOpened
        VideoWriter::write
####    Qt New Functions
        setWindowProperty
        getWindowProperty
        fontQt
        addText
        displayOverlay
        displayStatusBar
        setOpenGlDrawCallback
        saveWindowParameters
        loadWindowParameters
        createButton

**Comment by sajjadt** [comment]
Related [info](http://docs.opencv.org/3.0-beta/doc/user_guide/ug_intelperc.html) about supporting RealSense cameras from OpenCV 3 documentation.

**Comment by huningxin** [comment]
So far, we implemented `imread`, `imshow` and `VideoCapture`. Is it OK for MVP?

**Comment by huningxin** [comment]
CC @pancx

**Comment by sajjadt** [comment]
I think everything mentioned here can be done by native HTML5 elements. The only things that I think are missed are imdecode and  imencode. They will be helpful to access images raw data without the need to go through Canvas. However, then we need to build the library with necessary support for different picture compression such as jpeg and png.

**Comment by huningxin** [comment]
I suggest label it as a post MVP feature.

**Comment by huningxin** [comment]
@sajjadt , I open #206 specifically for `imgcodecs`. Then we can close this one.
