### ISSUE TITLE
Create comprehensive demos

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#69]
Create comprehensive demos for each category, like image processing, real-time video processing etc.,

**Comment by sajjadt** [comment]
I add few categories and demo ideas that can be easily included.

1. Basic operations (blend, invert, color conversion)
2. Canny edge detector
3. Adaptive threshold or equalizeHistogram
4. HAAR object detector (for detecting faces)
5. Filters: erode, blur
6. Motion detection and tracking
7. Stats: histogram
8. Image transformations: image warp, change perspective, 
9. Core: drawing?

**Comment by huningxin** [comment]
Turn the list to a check list
- [x] Basic operations (blend, invert, color conversion)
- [x] Canny edge detector
- [x] Adaptive threshold or equalizeHistogram
- [x] HAAR object detector (for detecting faces)
- [x] Filters: erode, blur
- [ ] Motion detection and tracking
- [x] Stats: histogram
- [ ] Image transformations: image warp, change perspective,
- [x] Core: drawing?

**Comment by huningxin** [comment]
https://github.com/huningxin/opencv.js/tree/master/samples

and 

https://codepen.io/collection/nJbkNo/

**Comment by huningxin** [comment]
Done for announcement. Will add more samples into https://github.com/huningxin/opencv.js
