### ISSUE TITLE
[ImgProc] some functions should be in the white list

### ISSUE THREAD

**Issue by ganwenyao** [huningxin/opencv#76]
Function Name | Location
------------ | -------------
cv.getRotationMatrix2D() | Geometric Transformations
cv.getPerspectiveTransform() | Geometric Transformations
cv.filter2D() | Smoothing Images
cv.morphologyEx() | Morphological Transformations
cv.getStructuringElement() | Morphological Transformations
cv.convertScaleAbs() | Image Gradients
cv.isContourConvex() | Contours 
cv.minAreaRect() | Contours 
cv.minEnclosingCircle() | Contours 
cv.fitLine()  | Contours 
cv.minMaxLoc() | Contours 
cv.convexityDefects() | Contours 
cv.pointPolygonTest() | Contours 
cv.matchShapes() | Contours 
cv.createCLAHE() | Histograms
cv.dft() | Image Transforms
cv.getOptimalDFTSize() | Image Transforms
cv.HoughLines()  | Hough Transform
cv.HoughLinesP()  | Hough Transform
cv.HoughCircles() | Hough Transform

**Comment by huningxin** [comment]
@ganwenyao , thanks for reporting this issue. Could you please specify the usages or references to python tutorials which are using these functions?

**Comment by ganwenyao** [comment]
@huningxin 
* cv.getRotationMatrix2D() can find an affine matrix of 2D rotation.
* cv.getPerspectiveTransform()  can find the transformation matrix from 4 points on the input image and corresponding points on the output image. 
* cv.filter2D() can convolve an arbitrary kernel with an image.
* cv.morphologyEx() can do Opening, Closing, Morphological Gradient and Top Hat morphological operation.
* cv.getStructuringElement() can generate elliptical/circular shaped kernels in morphological operation.
* cv.convertScaleAbs() can calculates absolute values, and converts the result to 8-bit.
* cv.isContourConvex() can check if a curve is convex or not. 
* cv.minAreaRect() finds a rotated rectangle of the minimum area.
* cv.minEnclosingCircle() can find the circumcircle of an object. 
* cv.fitLine() can fit a line to a set of points.
* cv.minMaxLoc() can finds the global minimum and maximum in an array.
* cv.convexityDefects() can finds the convexity defects of a contour.
* cv.pointPolygonTest() can finds the shortest distance between a point in the image and a contour.
* cv.matchShapes() enables us to compare two shapes, or two contours and returns a metric showing the similarity. 
* cv.createCLAHE() is Contrast Limited Adaptive Histogram Equalization.
* cv.dft(): Fourier Transform
* cv.getOptimalDFTSize()  returns the optimal DFT size for a given vector size.
* cv.HoughLines() cv.HoughLinesP() cv.HoughCircles(): Hough Transform

**Comment by ganwenyao** [comment]
* cv.isContourConvex() can check if a curve is convex or not. 
* cv.rectangle(rect) can draws a rectangle with Rect. 
* cv.minAreaRect() finds a rotated rectangle of the minimum area.
* cv.boxPoints() can finds the four vertices of a rotated rect. Useful to draw the rotated rectangle.
* cv.minEnclosingCircle() can find the circumcircle of an object. 
* cv.fitLine() can fit a line to a set of points.

**Comment by ganwenyao** [comment]
* cv.minMaxLoc() can finds the global minimum and maximum in an array.
* cv.createCLAHE() is Contrast Limited Adaptive Histogram Equalization.
* cv.CV_MAT_DEPTH(dtype) in cv.normalize()
* cv.dft() cv.dct(): Fourier Transform
* cv.getOptimalDFTSize()  returns the optimal DFT size for a given vector size.
* cv.HoughLines() cv.HoughLinesP() cv.HoughCircles(): Hough Transform
* cv.convertTo() has no default parameters

**Comment by huningxin** [comment]
As discussed in sync meeting, we will expose them. Let's follow up like this:
1. @huningxin will implement them in binding and report the file size difference.
2. @ganwenyao , please mark these functions in the google spreadsheet with specific color and notes in a column.
3. @sajjadt , please follow up with Vadim about these new functions.

**Comment by huningxin** [comment]
opencv.js size without and with these functions: 7039927 vs. 7211107 bytes

It increases about 167 KB.

**Comment by huningxin** [comment]
`minEnclosingCircle` is tricky, as http://docs.opencv.org/3.2.0/d3/dc0/group__imgproc__shape.html#ga8ce13c24081bbc7151e9326f412190f1, the third parameter is `float&` which returns the radius. However, according to https://github.com/kripken/emscripten/issues/611, embind doesn't support the non-const ref out parameters.

We may need to provide a wrapper to change the API signature in JS. Track it by https://github.com/huningxin/opencv/issues/126

**Comment by huningxin** [comment]
Similar issue to `minMaxLoc` http://docs.opencv.org/3.2.0/d2/de8/group__core__array.html#gab473bf2eb6d14ff97e89b355dac20707, it uses `double*` as return value. It's unfriendly for JS developer to provide the emscripten pointer to this API.

We may need to provide a wrapper to change the API signature in JS. Track it by https://github.com/huningxin/opencv/issues/127

**Comment by huningxin** [comment]
`createCLAHE` will be exposed as constructor of `CLAHE` object.

**Comment by ganwenyao** [comment]
These functions are marked with red color in the following google spreadsheet:
https://docs.google.com/spreadsheets/d/1BGsasC0Afd_sS2lljt7GVx1cl8VUwAfBlVtddtXsfYM/edit?usp=sharing
