### ISSUE TITLE
[Mat] support construction from JS array

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#79]
Sample code:
```
var vec = new Uint8Array(4);
var a = new cv.Mat(vec);
```
Exception
```
BindingError {name: "BindingError", message: "Cannot pass "0,0,0" as a UCharVector", stack: "BindingError: Cannot pass "0,0,0" as a UCharVector…939276), <anonymous>:4:34)↵    at <anonymous>:1:9"}
```

It expects a `UCharVector`. As API v2, it should take a `Uint8Array`.

**Comment by ganwenyao** [comment]
We can use the following constructor and Array data to construct a convolution kernel. @huningxin 
```C++
cv::Mat(int rows, int cols, int type, void* data, size_t step)
```

**Comment by huningxin** [comment]
@ganwenyao , that constructor is supported. I understand you need something like:
```js
cv.Mat(rows, cols, type, typedArray, step)
```
Is it?

**Comment by ganwenyao** [comment]
Yes

**Comment by huningxin** [comment]
As synced in Friday meeting:
* `cv::Mat(rows, cols, type, JSArray)` is preferred. As JavaScript implementation is easier and more efficient (1 memcpy vs. 2 memcpy). So I propose to implement `matFromArray(rows, cols, type, JSArray)` and `matFromImageData(imageData)` as #78 in JS helpers.
* `cv::Mat(int rows, int cols, int type, void* data, size_t step)` will be kept for future usage.
* `cv::Mat(const std::vector<unsigned char>& vector)` usage is not clear. Propose to remove it.
