### ISSUE TITLE
[Mat] element getters should follow lower camel case naming

### ISSUE THREAD

**Issue by huningxin** [huningxin/opencv#81]
It aligns to JS API convention. E.g. `get_uchar_at` should be `getUcharAt`.

**Comment by ganwenyao** [comment]
bitwise_and should be bitwiseAnd
bitwise_not should be bitwiseNot
bitwise_or should be bitwiseOr
bitwise_xor should be bitwiseXor

**Comment by huningxin** [comment]
> bitwise_and should be bitwiseAnd
> bitwise_not should be bitwiseNot
> bitwise_or should be bitwiseOr
> bitwise_xor should be bitwiseXor

I would prefer to keeping them as they are aligned to C++ API.

**Comment by huningxin** [comment]
For simplicity and alignment to C++ API, I propose the element getter naming as 
```
ucharAt
charAt
ushortAt
shortAt
intAt
floatAt
doubleAt
```
