### ISSUE TITLE
[ImgProc] different argument type between bindings and C++

### ISSUE THREAD

**Issue by ganwenyao** [huningxin/opencv#82]
In C++
```C++
void cv::drawContours(InputOutputArray image, InputArrayOfArrays contours, int contourIdx, const Scalar & color, int thickness = 1, int lineType = LINE_8, InputArray hierarchy = noArray(), int maxLevel = INT_MAX, Point offset = Point())		
```
In bindings
```javascript
void drawContours_wrapper(cv::Mat& arg1, const emscripten::val& arg2, int arg3, const Scalar& arg4, int arg5, int arg6, const cv::Mat& arg7, int arg8, Point arg9) {
        return cv::drawContours(arg1, emscripten::vecFromJSArray<cv::Mat>(arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9);
    }
```
* In C++, the arg2(InputArrayOfArrays contours) is vector<vector<Point>> type, but in bindings, arg2 is cv.MatVector type.
* In C++, the arg7(InputArray hierarchy) is vector\<Vec4i\> type, but in bindings, arg7 is cv.Mat type.
* noArray() is not supported in bindings.

**Comment by huningxin** [comment]
We need to exclude cv::Mat for vecFromJSArray.

noArray() support might be tricky as we don't support `InputOutputArray` yet.
