### ISSUE TITLE
[ImgProc] RotatedRect type are not exposed in bindings. 

### ISSUE THREAD

**Issue by ganwenyao** [huningxin/opencv#96]

**Comment by huningxin** [comment]
@ganwenyao , which API use this type? Could you please provide the test code? Thanks!

**Comment by ganwenyao** [comment]
@huningxin It's the return parameter of cv.fitEllipse(). and cv.boxPoints() can finds the four vertices of a RotatedRect.

**Comment by huningxin** [comment]
Thanks! And `cv::CamShift` also returns this type. I will take care of it.
